### ISSUE TITLE
[Question] Type hints?

### ISSUE THREAD

**Issue by Tatsh** [blackjack4494/yt-dlc#102]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I know this is a fork, and I'm wondering if you plan to regularly update from youtube-dl, but youtube-dl still supports ancient Python and can be a bit tricky to contribute to because of all the workaround functions that need to be used. I think type hints and static type checking (Mypy) can help in this regard. And perhaps, some bugs would be caught before an issue gets filed. A CI task for any new PR can be a static type check, which should give fairly high confidence that the code will work.

Are you interested in making such a change? Much of it would be regex based. This also means the core stuff like `_real_extract()` is not going to be allowed to change very often. But I think this is okay as it has been stable for a long time.

Type hints would also mean dropping support for Python < 3.6 and possibly 3.7 because of improvements in the type system. In fact 3.9 is best because it removes most of the extra imports (no `typing.List`, simply use `list` built-in).

On the ancient Python versions like 2.6/2.7, nobody should be using these as they are far past their time for support.

**Comment by xloem** [comment]
this is off topic: i wanted to add some thoughts around making a fork of youtube-dl in such a way that it is easy to merge.  could help consolidate the developer effort.  i'm interested in typehints and would enjoy adding them, but right now with so muhc fragmentation i'm skeptical that it is a good investment.

**Comment by blackjack4494** [comment]
This is out of scope for now. Python 2 should still be officially supported till beginning of next year. After that Python 2 Support will be not guaranteed (but may still work).
