### ISSUE TITLE
need zoomus extractor

### ISSUE THREAD

**Issue by HumHongeKamyaab** [blackjack4494/yt-dlc#107]
Please integrate it in `yt-dlc`. It is working properly.

https://github.com/ytdl-org/youtube-dl/pull/24751

**Comment by someziggyman** [comment]
Since the repo got nuked, I'm afraid that pull request can be hard to extract. If you have the extractor file for zoom and extractors.py with is being added, please zip and share those here. I guess, someone could implement this in a future build or apply it on their own in source code.
