### ISSUE TITLE
[Feature Request] GAnarchy project commit

### ISSUE THREAD

**Issue by SoniEx2** [blackjack4494/yt-dlc#11]
## Checklist

- [x] I'm reporting a feature request
- [N/A] I've verified that I'm running youtube-dlc version **2020.10.24**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

WRITE DESCRIPTION HERE

GAnarchy is a project I started about when the Mastodon developers refused to add a privacy-protecting feature I requested. it was originally created with the long-term goal of taking over the Mastodon project.

I kinda grew tired of Mastodon but I still stand behind GAnarchy. I think it's an useful project. I think forks of projects such as OpenWRT/LEDE, OpenSSL/LibreSSL, DooM/Sonic Robo Blast 2, and yt-dl/yt-dlc would all benefit from it in different ways. In particular for yt-dl/yt-dlc, I believe it can speed up development efforts even further (by completely decentralizing them), as well as provide strong censorship resistance (because it's so decentralized).

You can learn more about GAnarchy by checking out the subreddit at https://reddit.com/r/GAnarchy or one of the various instances such as https://ganarchy.github.io/ or https://ganarchy.autistic.space/. I've yet to do a proper write-up of it tho.

All it needs is a project maintainer to create a "project commit". They're formatted like so:

```
[Project] GAnarchy

A Project Page Generator written in Python, focused on giving forks of a
project the same visibility as the original repo.
```

**Comment by xloem** [comment]
I saw the youtube-dl maintainer read the wording of ganarchy's take on pull requests and rejected it: https://cache.tehsausage.com/ytdl/words.txt .  It seems ganarchy supports an effective equivalent of pull requests by placing forks ahead of the main branch if they are newer.

**Comment by SoniEx2** [comment]
Yeah, it replaces email patches and pull requests with a different system, based on putting forks ahead of the main branch if they are newer.

They're not really an "effective equivalent" tho. They're *comparable*, instead.
