### ISSUE TITLE
update to master branch didn't work

### ISSUE THREAD

**Issue by or78rXxZ** [blackjack4494/yt-dlc#111]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
README.md says

If you want to install the current master branch
python -m pip install git+https://github.com/blackjack4494/yt-dlc

I did and got

~ $ python -m pip install git+https://github.com/blackjack4494/yt-dlc
Collecting git+https://github.com/blackjack4494/yt-dlc
  Cloning https://github.com/blackjack4494/yt-dlc to ./tmp/pip-req-build-l95_Xs
Building wheels for collected packages: youtube-dlc
  Running setup.py bdist_wheel for youtube-dlc ... done
  Stored in directory: /home/foo/tmp/pip-ephem-wheel-cache-toP0uj/wheels/df/63/2f/10b7f1328dc3ae27de0d85f11781c3cbcfab295d5b9c5b57f7
Successfully built youtube-dlc
Installing collected packages: youtube-dlc
  Found existing installation: youtube-dlc 2020.10.31
    Uninstalling youtube-dlc-2020.10.31:
      Successfully uninstalled youtube-dlc-2020.10.31
  The script youtube-dlc is installed in '/home/foo/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed youtube-dlc-2020.10.25

Please tell this dumbass where I screwed up

**Comment by nicolaasjan** [comment]
Maybe because [version.py](https://raw.githubusercontent.com/blackjack4494/yt-dlc/master/youtube_dlc/version.py) still contains this:

```
from __future__ import unicode_literals

__version__ = '2020.10.25'
```

**Comment by october262** [comment]
try running sudo python -m pip install git+https://github.com/blackjack4494/yt-dlc
see if that works.

**Comment by or78rXxZ** [comment]
$ sudo python -m pip install git+https://github.com/blackjack4494/yt-dlc
Collecting git+https://github.com/blackjack4494/yt-dlc
  Cloning https://github.com/blackjack4494/yt-dlc to /tmp/pip-req-build-DQgRcE
Building wheels for collected packages: youtube-dlc
  Running setup.py bdist_wheel for youtube-dlc ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-bXTaMa/wheels/df/63/2f/10b7f1328dc3ae27de0d85f11781c3cbcfab295d5b9c5b57f7
Successfully built youtube-dlc
Installing collected packages: youtube-dlc
Successfully installed youtube-dlc-2020.10.25

I believe I miss labeled this question
The python -m pip install git+https://github.com/blackjack4494/yt-dlc does work
What I get is not what I expected
I was hoping for the updated code that would extract playlist
With all the recent yt troubles I did not know if I can post the command I am running

**Comment by or78rXxZ** [comment]
UPDATE: I said "I was hoping for the updated code that would extract playlist" which is not exactly correct.
The channel in question has a dozen or more playlist.
I am trying to get a list of the playlist.
Until recently this worked.
