### ISSUE TITLE
[Site Request] add support for youtube created playlist

### ISSUE THREAD

**Issue by IMIEEET** [blackjack4494/yt-dlc#116]
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running youtube-dlc version **2020.10.31**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

Youtube created Playlists cant be downloaded.
this is a example: 
https://www.youtube.com/watch?v=bDVEdZaFHA8&list=RDCLAK5uy_kLWIr9gv1XLlPbaDS965-Db4TrBoUTxQ8
youtube-dlc only downloads first one since its in url so i tried converting it to normal playlist: 
https://www.youtube.com/playlist?list=RDCLAK5uy_kLWIr9gv1XLlPbaDS965-Db4TrBoUTxQ8 (i know thats stupid but at least it opens in browser)
Verbose log with ' -f 140 --embed-thumbnail' args :
`[debug] System config: []`
`[debug] User config: []`
`[debug] Custom config: []`
`[debug] Command-line args: ['-v', '-f', '140', '--embed-thumbnail', 'https://www.youtube.com/watch?v=bDVEdZaFHA8&list=RDCLAK5uy_kLWIr9gv1XLlPbaDS965-Db4TrBoUTxQ8']`
`[debug] Loading archive file None`
`[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8`
`[debug] youtube-dlc version 2020.10.31`
`[debug] Python version 3.9.0 (CPython) - Linux-5.8.17-300.fc33.x86_64-x86_64-with-glibc2.32`
`[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1`
`[debug] Proxy map: {}`
`[youtube:playlist] Downloading playlist RDCLAK5uy_kLWIr9gv1XLlPbaDS965-Db4TrBoUTxQ8 - add --no-playlist to just download video bDVEdZaFHA8`
`[youtube:playlist] RDCLAK5uy_kLWIr9gv1XLlPbaDS965-Db4TrBoUTxQ8: Downloading page 1 of Youtube mix`
`[download] Downloading playlist: RDCLAK5uy_kLWIr9gv1XLlPbaDS965-Db4TrBoUTxQ8`
`[youtube:playlist] playlist RDCLAK5uy_kLWIr9gv1XLlPbaDS965-Db4TrBoUTxQ8: Collected 0 video ids (downloading 0 of them)`
`[download] Finished downloading playlist: RDCLAK5uy_kLWIr9gv1XLlPbaDS965-Db4TrBoUTxQ8`

**Comment by arter97** [comment]
Possibly related to #57 as well. @insaneracist 

I was able to confirm the same with "https://youtube.com/playlist?list=RDCLAK5uy_krjFmKbzWzkGvhqkYvvNnUbdrHy0QN1S8&feature=share&playnext=1".

**Comment by insaneracist** [comment]
It's assuming a playlist id starting with RD is a mix type, grabbing what it thinks is a video id from the last part of the playlist id, and then downloading an error page. It seems like playlists starting with `RDCLAK5uy_` are generated from Youtube Music. eg
https://www.youtube.com/playlist?list=RDCLAK5uy_m_h-nx7OCFaq9AlyXv78lG0AuloqW_NUA
https://www.youtube.com/playlist?list=RDCLAK5uy_k8GvsGbBT2D5lvGqOc6gAitzrcWVvecYI
