### ISSUE TITLE
[Question] How to add extractor without using import

### ISSUE THREAD

**Issue by joeland1** [blackjack4494/yt-dlc#127]
I have a my extractor file and the extractor works fine, but it will not be used unless it is imported in `__init__`. How would you get it to work without adding `import` statements like all the other extractors? Also, would it be possible to place the extractor file somewhere outside `youtube_dlc/extractor` directory and still use it? Sorry, still new to python.

works
```
from __future__ import unicode_literals
from .myextractor import *
```
does not work
```
from __future__ import unicode_literals
```

**Comment by insaneracist** [comment]
I may be misreading your question, but all the other extractors are imported, in `youtube_dlc/extractor/extractors.py`

**Comment by joeland1** [comment]
ah yes, thats what I was looking for. Thanks.
