### ISSUE TITLE
[YouTube] Unable to extract JS player URL

### ISSUE THREAD

**Issue by userlip** [blackjack4494/yt-dlc#13]
## Checklist

- [x ] I'm reporting a broken site support issue
- [x ] I've verified that I'm running youtube-dlc version **2020.10.24**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar bug reports including closed ones
- [x ] I've read bugs section in FAQ

## Verbose log

```
[Download] Debug: [youtube] dX3k_QDnzHE: Downloading webpage
[Download] Debug: [youtube] dX3k_QDnzHE: Downloading embed webpage
[Download] Error: ERROR: Unable to extract JS player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
[Download] Error: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/youtube_dlc/YoutubeDL.py", line 830, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dlc/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dlc/extractor/youtube.py", line 2050, in _real_extract
    ASSETS_RE, embed_webpage, 'JS player URL')
  File "/usr/local/lib/python3.6/dist-packages/youtube_dlc/extractor/common.py", line 1010, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dlc.utils.RegexNotFoundError: Unable to extract JS player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
```

## Description

This issue is happening around 2-3% of the time when downloading some Videos. This is one of the Videos (https://youtu.be/dX3k_QDnzHE), I am using yt-dlc in python embedded and not as a command line tool. I tried to make it as verbose as possible. If you need more info, just let me know.

As this issue is only happening sometimes, I know this is extremely hard to reproduce and fix, but maybe other people are experiencing this issue too and can share their experience with said issue.

If you need any more info, let me know

**Comment by merval** [comment]
After looking deeper, the download url is changing, which explains why it's ~2% of the time.
Occasionally the URL is embedded and hits this code:
https://github.com/blackjack4494/yt-dlc/blob/c3a7565610c452511804c3aefb1d00a9af58bdbb/youtube_dlc/extractor/youtube.py#L2043-L2050
Which is where it's failing.
Using --dump-pages, I can see the actual URL of the video changes:

[youtube] dX3k_QDnzHE: Downloading webpage
[youtube] Dumping request to https://www.youtube.com/watch?v=dX3k_QDnzHE&gl=US&hl=en&has_verified=1&bpctr=9999999999&disable_polymer=true

Vs:

[youtube] dX3k_QDnzHE: Downloading embed webpage
[youtube] Dumping request to https://www.youtube.com/embed/dX3k_QDnzHE?disable_polymer=true

This could be an artifact of the way youtube/google are routing their calls to videos.

**Comment by blackjack4494** [comment]
I have no issues here even trying it multiple times. Have you tried downloading that manually a few times?

**Comment by merval** [comment]
> I have no issues here even trying it multiple times. Have you tried downloading that manually a few times?

Interesting.. Outside of embedding it, it works without an issue.

**Comment by someziggyman** [comment]
I can confirm that this issue happens occasionally. Just try this playlist, for example:
ytdlc -v -F https://www.youtube.com/watch?list=PLexkHoTXo4UqctcWPvP246bV-Uhh7MNkQ

Run it at least 5 times and you will eventually get JS player error at some point on one or more videos. 3 times it worked fine, but then got this:

[download] Downloading video 6 of 35
[youtube] 3El_OdbaXjA: Downloading webpage
[youtube] 3El_OdbaXjA: Downloading embed webpage
ERROR: Unable to extract JS player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2101, in _real_extract
    ASSETS_RE, embed_webpage, 'JS player URL')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1010, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract JS player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Looks like this thread had a similar issue (even though it's some Obj-C framework). Hopefully it will help find a solution.
https://github.com/0xced/XCDYouTubeKit/issues/501

**Comment by raspatan** [comment]
Confirm it happens sometimes only. Using manual installation via wget using Ubuntu 16.04.

**Comment by masoudkazemi** [comment]
I'm using the last version (26.10.2020) and the issue is not resolved. I can provide logs too if it's needed. Thanks.

**Comment by ChoiYun** [comment]
> I'm using the last version (26.10.2020) and the issue is not resolved. I can provide logs too if it's needed. Thanks.

Same here. Even with the 2020.10.26, sometimes I still get the error.

**Comment by blackjack4494** [comment]
Just wait for next release or build yourself.

**Comment by nadermx** [comment]
Is there any specific pattern to the release dates?  Since this is already on the main branch installing via `pip install git+https://github.com/blackjack4494/yt-dlc` allows for it to work.  But then any cron you have that runs `pip install --upgrade youtube-dlc` reverts it back to the broken version.

**Comment by someziggyman** [comment]
> Is there any specific pattern to the release dates? Since this is already on the main branch installing via `pip install git+https://github.com/blackjack4494/yt-dlc` allows for it to work. But then any cron you have that runs `pip install --upgrade youtube-dlc` reverts it back to the broken version.

No need to wait for the release. Just download the source code, open Terminal and build a new binary from it. Works like a charm.

**Comment by nadermx** [comment]
so your saying if I just set my cron to `pip install git+https://github.com/blackjack4494/yt-dlc` that will work as a `pip install --upgrade youtube-dlc` but only from source?

**Comment by garoto** [comment]
`pip install --upgrade https://github.com/ytdl-org/youtube-dl/archive/master.zip`

**Comment by nadermx** [comment]
Garoto, that is a url to ytdl-org, not ytdlc, even so if you specifically `pip install git+https://github.com/blackjack4494/yt-dlc` installs `youtube-dlc 2020.10.25`  but `pip install youtube-dlc` installs `youtube-dlc 2020.10.26` so if you where to run `pip install --upgrade youtube-dlc` causing the issue when building from source

**Comment by roberdaniel** [comment]
Same thing here. Curl install over debian. Latest version to date.
This exactly same version worked well over a week ago more or less.
Regards.-

**Comment by NicoleKai** [comment]
Google must have broken the js protocol we were using because of the DMCA takedown and now we're gonna have to completely redo the program.
So rude >:(

**Comment by infraengineer-sre** [comment]
The same problem

```
youtube-dl -v https://youtu.be/rsUe7LFTSaU
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://youtu.be/rsUe7LFTSaU']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.09.20
[debug] Python version 3.8.6 (CPython) - macOS-10.15.7-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] rsUe7LFTSaU: Downloading webpage
[youtube] rsUe7LFTSaU: Downloading embed webpage
ERROR: Unable to extract JS player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 2100, in _real_extract
    jsplayer_url_json = self._search_regex(
  File "/usr/local/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 1010, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract JS player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by kraddock** [comment]
I believe this only happens to videos containing copyrighted music. I can download most of them using other tools (IDM, for example), but some videos are totally undownloadable, for example this one (press mute before playing, lol) - https://www.youtube.com/watch?v=NFjQALSVSwk

**Comment by nathamsr11** [comment]
running youtube-dl  as administrator  work well for me for all video
hope it'll help

**Comment by jgmullor** [comment]
> Nope, not working for any videos now
Same here...

@nathamsr11 official repo has been taken down by a [DMCA complaint](https://github.com/github/dmca/blob/master/2020/10/2020-10-23-RIAA.md)

**Comment by kraddock** [comment]
Nope, not working for any videos now

**Comment by ispa16** [comment]
its copyrighted, someone have an alternative ?

**Comment by gayan99x** [comment]
Running it with sudo worked for me
```shell
sudo youtube-dl "youtube-video-url"
```

**Comment by blindshare** [comment]
I don't know if this contributes to the discussion, but I realized the download works when selecting the streams separately.
So first you'd check the availability with "-F" and then pull the adequate streams.

**Comment by roberdaniel** [comment]
With the last update, version 2020.11.01.1 it is working again.
Many thanks to all contributors.

**Comment by beetrandahiya** [comment]
Yes true, its working with 2020.11.01.1
