### ISSUE TITLE
[Broken] ABC iview

### ISSUE THREAD

**Issue by iancourt** [blackjack4494/yt-dlc#15]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dlc version **2020.10.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: ['-f', 'best', '--merge-output-format', 'mkv']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://iview.abc.net.au/show/bluey/series/0/video/CH1903Q042S00']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.09.20
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg 2020-10-21-git-289e964873-full_build-www.gyan.dev, ffprobe 2020-10-21-git-289e964873-full_build-www.gyan.dev
[debug] Proxy map: {}
[debug] Using fake IP 1.152.104.99 (AU) as X-Forwarded-For.
[abc.net.au:iview] CH1903Q042S00: Downloading JSON metadata
[abc.net.au:iview] CH1903Q042S00: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 401: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\common.py", line 632, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\YoutubeDL.py", line 2238, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
```

## Description

All attempts to download content from ABC iview fail with the above error. This was working yesterday, but is failing today. I can confirm that videos are still playable in the browser (using an Australian-based VPN server).

**Comment by october262** [comment]
link works ok for me, did you try another VPN ??

**Comment by iancourt** [comment]
> link works ok for me, did you try another VPN ??

Thank you for testing!

To clarify, a VPN connect is (or was) only required for viewing in the browser. yt-dl and yt-dlc were able to get around the geoblock without a VPN connection.

In case that situation has changed as of today, I have tried with Australian VPN servers provided by both NordVPN and Surfshark when attempting to download using yt-dl and yt-dlc. I get the same 401 error with the VPN as without, with both yt-dl and yt-dlc.

**Comment by october262** [comment]
i didn't use a VPN, just tried like this >  youtube-dlc https://iview.abc.net.au/show/bluey/series/0/video/CH1903Q042S00

**Comment by iancourt** [comment]
Oddly, I’ve just successfully managed to download several videos, no VPN, and I’ve changed nothing. Same command is now working.

Apologies, we’ll consider this a false alarm for now!
