### ISSUE TITLE
URGENT(DMCA RELATED)

### ISSUE THREAD

**Issue by ReNardier** [blackjack4494/yt-dlc#152]
review these two, and remove the ones cited on the dmca
https://github.com/blackjack4494/yt-dlc/search?q=Timberlake
https://github.com/blackjack4494/yt-dlc/search?q=Taylor
and is suggest you review all the "demo" video links of all the video sites to remove all the possibly """offending""" links(id likely go scorched earth and then look into creating an account into each service and uploading Big Buck Bunny(and adding the link as the demo, or if a copy of Big Buck Bunny already exist on the service, link to it), or reviewing the links after removing them to see if they could cause issues and if they don't , add them back in)
ps: issue 10 might not be a bad idea and id suggest merging the changes from youtube-dl 2020.11.01.1 so that this is the apex version

**Comment by jbruchon** [comment]
Change the title to something that summarizes the issue? Would be very helpful. Generally, reports called things like "URGENT" or "help please" are low-priority because they don't actually look important.

**Comment by ZenulAbidin** [comment]
It’s only abcnews, mtv and netease music that have the videos you mentioned. And demo videos is the wrong term for them, you can see they’re in the `_TEST` object which means they are just test cases.

**Comment by chrisr11** [comment]
Better to just remove references to any music-related videos just to be safe.

**Comment by tygore587** [comment]
@ZenulAbidin I think youtube-dl was also blocked for having copyrighted music as test cases.

**Comment by virtadpt** [comment]
Yes.  That's what started this boondoggle.

**Comment by gfogus** [comment]
It would also be prudent to host elsewhere as a backup.

**Comment by ZenulAbidin** [comment]
> It would also be prudent to host elsewhere as a backup.

I already have backups of these repos on an offshore DMCA-ignoring provider, see https://gitea.datahoarding.agency

**Comment by blackjack4494** [comment]
this repo should be fine.
https://github.blog/2020-11-16-standing-up-for-developers-youtube-dl-is-back/
https://github.com/github/dmca/blob/master/2020/11/2020-11-16-RIAA-reversal-effletter.pdf
