### ISSUE TITLE
[Broken] www.mitele.es stopped working

### ISSUE THREAD

**Issue by Killogy** [blackjack4494/yt-dlc#162]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dlc version **2020.10.31**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
Error loading Python DLL 'E:\Temp\_MEI67122\python39.dll'.
LoadLibrary: No se puede encontrar el m¾dulo especificado.
In English something like " Cannot find module specified"


```

## Description

Example URL: https://www.mitele.es/programas-tv/cuarto-milenio/temporada-15/programa-630-40_1008680575033/player/

Usually I´m using the Firefox addon "Open with" https://addons.mozilla.org/es/firefox/addon/open-with/ to run mpv.exe and open the video stream. Latest working version is youtube-dlc 2020.10.26.

Opening a command promt and sending command youtube-dlc.exe -v https://www.mitele.es/programas-tv/cuarto-milenio/temporada-15/programa-630-40_1008680575033/player/ get...

Error loading Python DLL 'E:\Temp\_MEI67122\python39.dll'.
LoadLibrary: No se puede encontrar el m¾dulo especificado.
In English something like " Cannot find module specified"

Running youtube-dlc 2020.10.26 video is downloading and Verbose log is:

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.mitele.es/programas-tv/cuarto-mil
enio/temporada-15/programa-630-40_1008680575033/player']
[debug] Loading archive file None
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dlc version 2020.10.26
[debug] Python version 3.8.6 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[MiTele] programa-630-40_1008680575033: Downloading webpage
[MiTele] 67d73d53-33ec-4e87-8916-f6c38696dee9: Downloading config JSON
[MiTele] 67d73d53-33ec-4e87-8916-f6c38696dee9: Downloading gbx JSON
[MiTele] 67d73d53-33ec-4e87-8916-f6c38696dee9: Downloading caronte JSON
[MiTele] 67d73d53-33ec-4e87-8916-f6c38696dee9: Downloading cerbero JSON
[MiTele] 67d73d53-33ec-4e87-8916-f6c38696dee9: Downloading m3u8 information
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://vod.mitele.es/hls/VOD/67d73d53-33ec-4e87
-8916-f6c38696dee9/67d73d53-33ec-4e87-8916-f6c38696dee9.,365,660,1190,2145,3200,
.mp4.csmil/index-f5-v1-a1.m3u8?hdntl=exp=1605130840~acl=/hls/VOD/67d73d53-33ec-4
e87-8916-f6c38696dee9/*~data=hdntl~hmac=5fda73e34ceca76b8a5f5aa734f2591d566ae1f2
691f3860d926aa971730d8a4'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 756
[download] Destination: Cuarto Milenio 2020 Programa 630-67d73d53-33ec-4e87-8916
-f6c38696dee9.mp4
[download]   0.4% of ~3.15GiB at 12.84MiB/s ETA 04:43

**Comment by crbelaus** [comment]
@Killogy have you made it work? I am facing the same problem.

**Comment by Killogy** [comment]
@crbelaus yes is solved because latest version fixed it.
