### ISSUE TITLE
[Broken] XTube is broken

### ISSUE THREAD

**Issue by waldens** [blackjack4494/yt-dlc#17]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dlc version **2020.10.26**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
D:\Dropbox\Technical_Backup\warehouse\yt-dlc>py -3 -m youtube_dlc "https://www.xtube.com/video-watch/19yo-buddy-sucking-me-off-and-swallowing-41643481" -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.xtube.com/video-watch/19yo-buddy-sucking-me-off-and-swallowing-41643481', '-v']
[debug] Loading archive file None
[debug] Encodings: locale cp936, fs utf-8, out utf-8, pref cp936
[debug] youtube-dlc version 2020.10.25
[debug] Git HEAD: 6410992da
[debug] Python version 3.6.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg git-2020-07-16-d11cc74, ffprobe git-2020-07-16-d11cc74
[debug] Proxy map: {'https': 'http://127.0.0.1:4411', 'http': 'http://127.0.0.1:4411'}
[XTube] 19yo-buddy-sucking-me-off-and-swallowing: Downloading webpage
Traceback (most recent call last):
  File "C:\Python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Dropbox\Technical_Backup\warehouse\yt-dlc\youtube_dlc\__main__.py", line 19, in <module>
    youtube_dlc.main()
  File "D:\Dropbox\Technical_Backup\warehouse\yt-dlc\youtube_dlc\__init__.py", line 487, in main
    _real_main(argv)
  File "D:\Dropbox\Technical_Backup\warehouse\yt-dlc\youtube_dlc\__init__.py", line 477, in _real_main
    retcode = ydl.download(all_urls)
  File "D:\Dropbox\Technical_Backup\warehouse\yt-dlc\youtube_dlc\YoutubeDL.py", line 2096, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "D:\Dropbox\Technical_Backup\warehouse\yt-dlc\youtube_dlc\YoutubeDL.py", line 830, in extract_info
    ie_result = ie.extract(url)
  File "D:\Dropbox\Technical_Backup\warehouse\yt-dlc\youtube_dlc\extractor\common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "D:\Dropbox\Technical_Backup\warehouse\yt-dlc\youtube_dlc\extractor\xtube.py", line 103, in _real_extract
    if not isinstance(sources, dict):
UnboundLocalError: local variable 'sources' referenced before assignment
```

## Description

Regex used in line 93 of `xtube.py` is not working anymore. could be half-fixed by changing from 
`r'playerConf\s*=\s*({.+?})\s*,\s*\n', webpage, 'config',`
to
`r'playerConf\s*=\s*({.+?})\s*,\s*loaderConf', webpage, 'config',`

but varible `config` in line 92 still cannot get the correct assignment because output of `_parse_json()` is still invalid json even though `transform_source=js_to_json` has been used. the reason seems that the values of keys "defaultQuality", "autoPlay" are like `!0`, `!1`, in which condition `js_to_json` cannot handle correctly, probably some fix need to be done in `def js_to_json()` of `utils.py`. idk how to fix this issue. the logic of `def js_to_json()` is too complex for me.<img alt="ghe-emoji" title=":_onion_head_crying4:" src="https://cloud.githubusercontent.com/assets/136959/13371446/f90c6e9a-dceb-11e5-8b75-d6200ed0c0f7.gif">

**Comment by merval** [comment]
You're right, the regex doesn't match. 'config' doesn't exist in the playerConf line, which is leading to an empty dictionary.
It appears the structure of the page might have changed, the way the regex is written it would only capture _part of_ the JSON it needs but there is no newline at the end. Here is what the regex would capture without the newline at the end: ```playerConf={startOffset:0,productUrl:"https://www.xtube.com/video-watch/19yo-buddy-sucking-me-off-and-swallowing-41643481",mainRoll:{mediaDefinition:[{defaultQuality:!1,format:"mp4",quality:720,videoUrl:"https://cdn1-l-hw-e7.xtube.com/videos/201910/04/41643481/xtube_mp4_720.mp4?ttl=1603800676&hash=c5cb30f1055a0189f38dc490508c3b4c"}```

But, looking at the page source, the regex may actually need to be: ```playerConf\s*=\s*({.+?}),loaderConf```
With 'config' missing, the _parse_json throws ```WARNING: [XTube] 41643481: Failed to parse JSON Expecting value: line 1 column 166 (char 165)```

It appears that for a long time (something like 4 years line 62 here: https://github.com/blackjack4494/yt-dlc/commit/1b734adb2d3bb17af67b5fef933a6fafe71e4cf4) sources was defined outside of any if statement, but with the last extractor fix sources is defined inside of an if statement, which means unless you have an else on your if statement OR define it globally, it's broken. (where it broke: https://github.com/blackjack4494/yt-dlc/commit/e88b450771027e3a36e7b3721e0bc1f105331cf7)
