### ISSUE TITLE
[Question]Python implementation. 

### ISSUE THREAD

**Issue by itkfilelor** [blackjack4494/yt-dlc#171]
## Checklist

- [x ] I'm asking a question
- [x ] I've looked through the README and FAQ for similar questions
- [x ] I've searched the bugtracker for similar questions including closed ones

## Question

I have a daily automation written in python3 which has since been broken with the newest changes on YT's side. It would appear your fork has fixed it. 
Before I gut my script, if I port over to dlc from dl, does this work the same command wise as the original module? (Excepting that I would import dlc instead of dl of course.)
Sorry if I missed any FAQ's already addressing this. 
Thanks. 
Edit: forgot to include python3 in question.

**Comment by pukkandan** [comment]
Yes. Only the module name has to be changed
