### ISSUE TITLE
Update the invidious instances list

### ISSUE THREAD

**Issue by TheFrenchGhosty** [blackjack4494/yt-dlc#179]
## Checklist

- [x] I've searched the bugtracker for similar issues including closed ones

## Description

The invidious instances list is heavily outdated, and include a lot of dead instances (while missing a lot of new ones).

https://github.com/blackjack4494/yt-dlc/blob/master/youtube_dlc/extractor/youtube.py#L454

It would be nice if you could update it.

The list is here: https://github.com/iv-org/documentation/blob/master/Invidious-Instances.md

PS: it would be nice if you could also add the semi-private instance I maintain for some users: https://invidious.pussthecat.org

**Comment by blackjack4494** [comment]
okay. can you name those broken ones?

**Comment by TheFrenchGhosty** [comment]
@blackjack4494 Nothing is really broken, it's just outdated. You can see the list here: https://github.com/iv-org/documentation/blob/master/Invidious-Instances.md

**Comment by TheFrenchGhosty** [comment]
Done in yt-dlp, closing.
