### ISSUE TITLE
[Question] SoundCloud Go+ HQ downloads

### ISSUE THREAD

**Issue by tehwolf1337** [blackjack4494/yt-dlc#18]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Does this fork have ability to download HQ tracks from SoundCloud with Go+ subscription using just login and password?

**Comment by blackjack4494** [comment]
yes.
