### ISSUE TITLE
[Question] What is the difference between the 32-bit and 64-bit yt-dlc binary?

### ISSUE THREAD

**Issue by chrisr11** [blackjack4494/yt-dlc#192]
Hi,

The 64-bit binary doesn't work on my 64-bit Windows so I am using the 32-bit binary file. What's the difference between these two? Will 32-bit binary work on all 64-bit architecture?

**Comment by michealespinola** [comment]
Both versions (`youtube-dlc.exe` and `youtube-dlc_x86.exe`) work on my 64-bit Windows 10 system.  Sorry, but I have to ask: Are you positive that your computer is 64-bit?

**Comment by chrisr11** [comment]
Yep, 100% sure that it is 64-bit but I heard that on Windows 7, the 64-bit doesn't work so I'm using the 32-bit and that works fine. That's why I wanna know the difference between them. Is the performance better on the 64-bit version?

**Comment by Killogy** [comment]
@chrisr11 I´m running Windows 7 64-bit Ultimate and youtube-dlc.exe working properly.

**Comment by michealespinola** [comment]
@chrisr11 The performance difference is imperceivable to me based on how I use it in a limited capacity. Perhaps it would be registerable in larger bulk processing.
