### ISSUE TITLE
[Broken] ytsearch/date not returning results

### ISSUE THREAD

**Issue by ledmaster** [blackjack4494/yt-dlc#201]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dlc version **2020.11.11**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dlc ytsearch10:"data science" --flat-playlist -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['ytsearch10:data science', '--flat-playlist', '-v']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dlc version 2020.11.11-3
[debug] Python version 3.7.6 (CPython) - Darwin-19.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[download] Downloading playlist: data science
[youtube:search] query "data science": Downloading page 1
[youtube:search] playlist data science: Downloading 0 videos
[download] Finished downloading playlist: data science

youtube-dlc ytsearch10:"machine learning" --flat-playlist -v 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['ytsearch10:machine learning', '--flat-playlist', '-v']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dlc version 2020.11.11-3
[debug] Python version 3.7.6 (CPython) - Darwin-19.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[download] Downloading playlist: machine learning
[youtube:search] query "machine learning": Downloading page 1
[youtube:search] playlist machine learning: Downloading 10 videos
[download] Downloading video 1 of 10
[download] Downloading video 2 of 10
[download] Downloading video 3 of 10
[download] Downloading video 4 of 10
[download] Downloading video 5 of 10
[download] Downloading video 6 of 10
[download] Downloading video 7 of 10
[download] Downloading video 8 of 10
[download] Downloading video 9 of 10
[download] Downloading video 10 of 10
[download] Finished downloading playlist: machine learning
```

## Description

Hi everyone.

It seems youtube-dlc is having trouble finding the results for some search terms. 

Above I put the code for retrieving results for "data science" and "machine learning".

It finds results for "machine learning" but not for "data science".

This happens not only with normal search but ```ytsearchdate``` too.

Can you try to reproduce it please? I am using the latest version.

Thanks!

**Comment by colethedj** [comment]
Seems to be YouTube sometimes adding e.g. "promoted" content into the searches, moving the index location of the actual videos data in the list than what is manually specified in the code. In theory this would also affect the normal ytsearch at times as its part of the same code.
Should be an easy fix to make it not dependent on index position, I'll submit a draft PR shortly.
