### ISSUE TITLE
[Site Request] Bitchute embedded videos

### ISSUE THREAD

**Issue by tjesp** [blackjack4494/yt-dlc#204]
As far as I know youtube-dlc already supports Bitchute but I am asking for Bitchute videos embedded on other sites like this:

https://davidicke.com/2020/11/13/there-is-no-virus-when-that-penny-drops-all-else-follows-david-icke-dot-connector-please-share/

(the video is below the "How they pulled off the pandemic" header). This is a bitchute video but its hard to even click on it unlike a youtube video to be brought to their site. I actually have to inspect the code to get the link.

I know youtube-dl(c) supports embedded youtube videos already so I hope you can add support for this.

**Comment by pukkandan** [comment]
The issue seems to be that there is also a youtube video in the page. Once youtube-dlc finds the youtube video, it just tries to download it. Can you share an example url with only a bitchute video embedded?

**Comment by tjesp** [comment]
There is only a bitchute video here:

https://davidicke.com/2020/11/15/how-to-deal-with-police-and-all-authority-under-common-law-the-real-law-of-the-land-remember-that-governments-and-police-are-private-corporations-that-operate-under-contractual-agreements-and-if-we/

Part of my problems finding examples is that I have other examples but they are on a forum behind a paywall. (I use cookies.txt with youtube-dlc).

**Comment by pukkandan** [comment]
I don't know how to fix the first case.
> Once youtube-dlc finds the youtube video, it just tries to download it.

I will make a PR for the case when there are only bitchute videos in the page
