### ISSUE TITLE
[YT] Add support for mix playlist of RDCM type Collected 0 video ids

### ISSUE THREAD

**Issue by someziggyman** [blackjack4494/yt-dlc#216]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dlc version **2020.10.31**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[youtube:playlist] RDCMUCGZ0LgTmAJn9Banetdr_ZFg: Downloading page 1 of Youtube mix
[download] Downloading playlist: RDCMUCGZ0LgTmAJn9Banetdr_ZFg
[youtube:playlist] playlist RDCMUCGZ0LgTmAJn9Banetdr_ZFg: Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: RDCMUCGZ0LgTmAJn9Banetdr_ZFg
```

## Description

Reported this problem here https://github.com/blackjack4494/yt-dlc/issues/33#issuecomment-725972175 but that case is still marked a closed. So creating this new one for visibility.

I found a curios YT Mix playlist that still has this Collected 0 video ids
https://www.youtube.com/playlist?list=RDCMUCGZ0LgTmAJn9Banetdr_ZFg

got it from here:
https://www.youtube.com/watch?v=_OgBDRPoIcA&list=RDCMUCGZ0LgTmAJn9Banetdr_ZFg&start_radio=1&t=0

Another ID that fails is: RDCMUCmvAV_za1KXGXSgC0o0v9DQ
Full link: https://www.youtube.com/watch?v=jmDtqcf0v_0&list=RDCMUCmvAV_za1KXGXSgC0o0v9DQ&start_radio=1
https://www.youtube.com/playlist?list=RDCMUCmvAV_za1KXGXSgC0o0v9DQ

Could be some new or unknown mix playlist format type cause both start with RDCM

[youtube:playlist] RDCMUCGZ0LgTmAJn9Banetdr_ZFg: Downloading page 1 of Youtube mix
[download] Downloading playlist: RDCMUCGZ0LgTmAJn9Banetdr_ZFg
[youtube:playlist] playlist RDCMUCGZ0LgTmAJn9Banetdr_ZFg: Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: RDCMUCGZ0LgTmAJn9Banetdr_ZFg

Must mention that all other playlist (mix, regular, /videos) are working just fine.

Looks like RDCM is prefix for a channel mix rather than video mix, UCGZ0LgTmAJn9Banetdr_ZFg and UCmvAV_za1KXGXSgC0o0v9DQ are the channel ids

**Comment by pukkandan** [comment]
https://www.youtube.com/playlist?list=RDCMUCGZ0LgTmAJn9Banetdr_ZFg will always fail because it such a url does not exist. Mix playlists can only be accessed from video page. 

https://www.youtube.com/watch?v=jmDtqcf0v_0&list=RDCMUCmvAV_za1KXGXSgC0o0v9DQ&start_radio=1 on the other hand, can be fixed
