### ISSUE TITLE
[Broken] YouTube channel pages fail to download - "Downloading 0 videos"

### ISSUE THREAD

**Issue by HeySteets** [blackjack4494/yt-dlc#219]
#55  Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dlc version **2020.10.31**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: ['--retries', '15', '--ignore-errors', '--continue', '--write-description', '--write-info-json', '--write-thumbnail', '--console-title', '--verbose', '--merge-output-format', 'mkv', '--write-sub', '--write-auto-sub', '--sub-format', 'srt', '--prefer-ffmpeg', '--add-metadata']
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/channel/UCK8sQmJBp8GCxrOtXWBpyEA']
[debug] Loading archive file None
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dlc version 2020.10.31
[debug] Python version 3.8.6 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg N-93726-g7eba264513, ffprobe N-93726-g7eba264513
[debug] Proxy map: {}
[youtube:channel] UCK8sQmJBp8GCxrOtXWBpyEA: Downloading channel page
[youtube:playlist] UUK8sQmJBp8GCxrOtXWBpyEA: Downloading webpage
[download] Downloading playlist: UUK8sQmJBp8GCxrOtXWBpyEA
[youtube:playlist] playlist UUK8sQmJBp8GCxrOtXWBpyEA: Downloading 0 videos
[download] Finished downloading playlist: UUK8sQmJBp8GCxrOtXWBpyEA
```

## Description

Attempting to download a YouTube channel by specifying their channel URL fails, with the downloader saying it is "Downloading 0 videos". This appears to affect URLs formatted as youtube.com/user, youtube.com/c/user, and youtube.com/channel/user. I've tried this in both youtube-dlc and youtube-dl, and the issue appears in both, so this may be with YouTube changing something on their end.  Specifying the URL for a channel's "[Uploads from %USER%](https://www.youtube.com/playlist?list=UUK8sQmJBp8GCxrOtXWBpyEA)" playlist does still work, though. I've tried this on multiple devices including two computers, a laptop, several VMs, and an Android phone, with and without configuration files, from different IP addresses, through VPNs, and just about everything else. (All using the latest 10.31 release.)

**Comment by leodomi** [comment]
You are not using the latest version of youtube-dlc.
This problem with youtube playlists is fixed, use version **2020.11.11-3**

**Comment by someziggyman** [comment]
I can confirm it works just fine with the latest version - 2020.11.11-3
Assume this issue can be closed.

**Comment by HeySteets** [comment]
Just got the latest version, still had the problem. Realized the version in my PATH was out-of-date. Yeah, that'll do it...
