### ISSUE TITLE
[Site Request] Support Spotify

### ISSUE THREAD

**Issue by SlavKing98** [blackjack4494/yt-dlc#234]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dlcc version **2020.10.31** (2020.11.11-3)
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights (I don't care tbh)
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://open.spotify.com/track/2nNwaUrxRDSPkdZ44WC0qH

## Description

Currently, there is literally no free and working spotify downloader on the internet. I tried all available downloaders that claim to be able to download music from spotify. Some of them simply do not work or are outdated, while the rest of them **do not download from spotify, but instead retrieve names of songs and perform a youtube search and download them from youtube.** That does not work if there is a song that is available only on spotify and nowhere else.

If someone decides to add a spotify support to yt-dlc, please make sure to:

1. Download from spotify directly instead of getting song names and performing a youtube search
2. Do not perform any lossy conversion after download

Many software I tried offer to convert downloaded music to MP3, which, by definition, reduces the quality. Add an option to yt-dlc to keep the original downloaded song.

**Comment by samoht0** [comment]
Spotify uses Widevine DRM. So, nobody will decide to create an extractor for youtube-dlc, because that would need to break DRM (if even possible).
RIAA + DMCA + youtube-dl, you know? Please consider closing the issue.

**Comment by SlavKing98** [comment]
> Spotify uses Widevine DRM. So, nobody will decide to create an extractor for youtube-dlc, because that would need to break DRM (if even possible).
RIAA + DMCA + youtube-dl, you know? Please consider closing the issue.

DMCA affects only people living in USA and similar countries whose jurisdiction systems recognize copyright laws. In my country, violating copyright laws or "stealing" intelectual property is allowed. Why do we need to host yt-dlc on GitHub? I would like to work with other people who are interested in making a good spotify extractor and we can share it on some safe website, then we can make it as an extension to yt-dlc. Is anyone interested?

**Comment by samoht0** [comment]
>I would like to work with other people who are interested in making a good spotify extractor and we can share it on some safe website, then we can make it as an extension to yt-dlc. Is anyone interested?

Well then, forking, hosting the source and trying your luck to find contibutors. But nothing, that will happen here. Sorry.

**Comment by blackjack4494** [comment]
drm not supported.
