### ISSUE TITLE
Comedy Central merging files

### ISSUE THREAD

**Issue by jriker1** [blackjack4494/yt-dlc#239]
Trying to get YouTube-DLC to download comedy central shows. It's working but unlike all the other channels I use it for it doesn't merge the segments together. I get like 7 pieces. Example URL is:

http://www.cc.com/episodes/yy0vjs/south-park-the-pandemic-special-season-24-ep-2401

Tried several different permutations of calling it but two examples are:

youtube-dlc --ap-mso Comcast_SSO --merge-output-format mkv --ap-username <mylogin> --ap-password <mypassword> --postprocessor-args "-strict experimental" -f "bestvideo+bestaudio/best" http://www.cc.com/episodes/yy0vjs/south-park-the-pandemic-special-season-24-ep-2401

and what I normally use:

youtube-dlc --ap-mso Comcast_SSO --ap-username <mylogin> --ap-password <mypassword> http://www.cc.com/episodes/yy0vjs/south-park-the-pandemic-special-season-24-ep-2401

Any idea what's going on? For reference I basically get:

South Park_September 30, 2020_24_2401_The Pandemic Special_Act 1-0c8b3ae3-1242-4618-8a1b-a6a8b005244e.mp4
South Park_September 30, 2020_24_2401_The Pandemic Special_Act 2-6692de85-19c1-4854-be58-aff64bb8005b.mp4
South Park_September 30, 2020_24_2401_The Pandemic Special_Act 3-49c1e3c7-1ef3-4c07-9aeb-03f632368e77.mp4
South Park_September 30, 2020_24_2401_The Pandemic Special_Act 4-fc1056fa-2a05-45c6-bcb0-30196b36e9a1.mp4
South Park_September 30, 2020_24_2401_The Pandemic Special_Act 5-e4cd0242-6cb2-4472-bfef-99af09024a09.mp4
South Park_September 30, 2020_24_2401_The Pandemic Special_Act 6-2eb2c231-8d6c-42bc-ac3b-7efdcc859c9b.mp4
South Park_September 30, 2020_24_2401_The Pandemic Special_Act 7-c0c54232-624d-4dfe-8f90-a131fa5e08db.mp4

Also tried thru the SouthPark site itself at:

https://southpark.cc.com/episodes/yy0vjs/south-park-the-pandemic-special-season-24-ep-1

but it wouldn't download the XML for the show so maybe not part of the app for that piece.

On Windows version 2020-11-11 by the way.

Also note if I give an output filename like -o SouthPark.mp4 it only downloads the first segment, renames it and stops.  I get at the end of the output:

3469997731.ts' for reading
frame=14216 fps=246 q=-1.0 Lsize=  189907kB time=00:09:52.89 bitrate=2623.9kbits/s speed=10.3x
video:180262kB audio:9184kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.243260%
[ffmpeg] Downloaded 194464712 bytes
[download] 100% of 185.46MiB in 00:58
[download] 100% of 185.46MiB in 00:58
[download] Downloading video 2 of 7
[download] SouthPark.mp4 has already been downloaded
[download] 100% of 185.46MiB
[download] Downloading video 3 of 7
[download] SouthPark.mp4 has already been downloaded
[download] 100% of 185.46MiB
[download] Downloading video 4 of 7
[download] SouthPark.mp4 has already been downloaded
[download] 100% of 185.46MiB
[download] Downloading video 5 of 7
[download] SouthPark.mp4 has already been downloaded
[download] 100% of 185.46MiB
[download] Downloading video 6 of 7
[download] SouthPark.mp4 has already been downloaded
[download] 100% of 185.46MiB
[download] Downloading video 7 of 7
[download] SouthPark.mp4 has already been downloaded
[download] 100% of 185.46MiB
[download] Finished downloading playlist: The Pandemic Special

**Comment by StevenDTX** [comment]
I use powershell for most of my downloading, simply because thats what I know.  After the downloads, I create a concat file, then use ffmpeg to join them.

```
		foreach ($i in $MP4s)
			{	$i | Add-Member -membertype NoteProperty -name concat -value ("file '" + $i.FullName + "'") -Force	}

		$MP4s.concat | Out-File $concatpath -Encoding ascii -Force

		& c:\support\ffmpeg\bin\ffmpeg.exe -safe 0 -f concat -i $concatpath -vcodec copy -acodec copy -scodec srt $SaveAs2
```

**Comment by jriker1** [comment]
Thanks for the thought. I am using C# and have done something similar but thought youtube-dlc was supposed to merge content but maybe Comedy Central is the only one I've run into that creates multiple video/audio files vs just merging a separate audio/video together.

**Comment by StevenDTX** [comment]
> 
> 
> Thanks for the thought. I am using C# and have done something similar but thought youtube-dlc was supposed to merge content but maybe Comedy Central is the only one I've run into that creates multiple video/audio files vs just merging a separate audio/video together.

Ive been using youtube-dl, and now -dlc, for many, many years and I dont ever recall the mtvnetworks segments getting joined by youtube-dl.

**Comment by blackjack4494** [comment]
Yup MTV Network sites (comedy central, southpark etc) are a bit special. They deliver segmented files as they play ads in between those segments. It's possible to implement some special case for affected extractors to merge them in post processing. We had a discussion about that somewhere (dunno if it was in currently dmca blocked youtube-dlc fork).
