### ISSUE TITLE
[Broken] Facebook download of private (friends-only) video fails with ExtractorError

### ISSUE THREAD

**Issue by digital-pet** [blackjack4494/yt-dlc#240]
# Please read and comprehend the entire issue before responding, thank you!

## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dlc version **2020.11.11-3**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.facebook.com/video.php?v=10158180747884436', '--username', 'PRIVATE', '--password', 'PRIVATE', '--verbose']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dlc version 2020.11.11-3
[debug] Python version 3.8.2 (CPython) - Linux-4.4.0-19041-Microsoft-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[facebook] Downloading login page
[facebook] Logging in
[facebook] 10158180747884436: Downloading webpage
[facebook] 10158180747884436: Downloading webpage
[facebook] 10158180747884436: Downloading webpage
ERROR: Cannot parse data; please report this issue on https://github.com/blackjack4494/yt-dlc . Make sure you are using the latest version; see  https://github.com/blackjack4494/yt-dlc  on how to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/sofia-wsl/.local/lib/python3.8/site-packages/youtube_dlc/YoutubeDL.py", line 830, in extract_info
    ie_result = ie.extract(url)
  File "/home/sofia-wsl/.local/lib/python3.8/site-packages/youtube_dlc/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/home/sofia-wsl/.local/lib/python3.8/site-packages/youtube_dlc/extractor/facebook.py", line 482, in _real_extract
    _, info_dict = self._extract_from_url(
  File "/home/sofia-wsl/.local/lib/python3.8/site-packages/youtube_dlc/extractor/facebook.py", line 380, in _extract_from_url
    raise ExtractorError('Cannot parse data')
youtube_dlc.utils.ExtractorError: Cannot parse data; please report this issue on https://github.com/blackjack4494/yt-dlc . Make sure you are using the latest version; see  https://github.com/blackjack4494/yt-dlc  on how to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
```

## Description

Attempting to download a private youtube video from a friend's post results in the above error and the video fails to download.

I have tried multiple videos set to "friends only" with both youtube video link formats
https://www.facebook.com/[username]/videos/[video-id]/
and 
https://www.facebook.com/video.php?v=[video-id]

 any (Edit:)friends-only video you have access to should suffice

**Comment by october262** [comment]
> ## Checklist
> * [x]  I'm reporting a broken site support
> * [x]  I've verified that I'm running youtube-dlc version **2020.11.11-3**
> * [x]  I've checked that all provided URLs are alive and playable in a browser
> * [x]  I've checked that all URLs and arguments with special characters are properly quoted or escaped
> * [x]  I've searched the bugtracker for similar issues including closed ones
> 
> ## Verbose log
> ```
> [debug] System config: []
> [debug] User config: []
> [debug] Custom config: []
> [debug] Command-line args: ['https://www.facebook.com/video.php?v=10158180747884436', '--username', 'PRIVATE', '--password', 'PRIVATE', '--verbose']
> [debug] Loading archive file None
> [debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
> [debug] youtube-dlc version 2020.11.11-3
> [debug] Python version 3.8.2 (CPython) - Linux-4.4.0-19041-Microsoft-x86_64-with-glibc2.29
> [debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
> [debug] Proxy map: {}
> [facebook] Downloading login page
> [facebook] Logging in
> [facebook] 10158180747884436: Downloading webpage
> [facebook] 10158180747884436: Downloading webpage
> [facebook] 10158180747884436: Downloading webpage
> ERROR: Cannot parse data; please report this issue on https://github.com/blackjack4494/yt-dlc . Make sure you are using the latest version; see  https://github.com/blackjack4494/yt-dlc  on how to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
> Traceback (most recent call last):
>   File "/home/sofia-wsl/.local/lib/python3.8/site-packages/youtube_dlc/YoutubeDL.py", line 830, in extract_info
>     ie_result = ie.extract(url)
>   File "/home/sofia-wsl/.local/lib/python3.8/site-packages/youtube_dlc/extractor/common.py", line 532, in extract
>     ie_result = self._real_extract(url)
>   File "/home/sofia-wsl/.local/lib/python3.8/site-packages/youtube_dlc/extractor/facebook.py", line 482, in _real_extract
>     _, info_dict = self._extract_from_url(
>   File "/home/sofia-wsl/.local/lib/python3.8/site-packages/youtube_dlc/extractor/facebook.py", line 380, in _extract_from_url
>     raise ExtractorError('Cannot parse data')
> youtube_dlc.utils.ExtractorError: Cannot parse data; please report this issue on https://github.com/blackjack4494/yt-dlc . Make sure you are using the latest version; see  https://github.com/blackjack4494/yt-dlc  on how to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
> ```
> 
> ## Description
> Attempting to download a private youtube video from a friend's post results in the above error and the video fails to download.
> 
> I have tried multiple videos set to "friends only" with both youtube video link formats, any one you have access to should suffice
> [https://www.facebook.com/[username]/videos/[video-id]/](https://www.facebook.com/%5Busername%5D/videos/%5Bvideo-id%5D/)
> and
> [https://www.facebook.com/video.php?v=[video-id]](https://www.facebook.com/video.php?v=%5Bvideo-id%5D)

both of your sample links come up as page missing/broken

**Comment by digital-pet** [comment]
They are simply templates, showing the format of youtube video links.

As the videos affected are ones set to friends only and I do not know your facebook friends, I cannot provide sample links that you can access. You can test this yourself by finding a video on your feed set to "friends only" and attempting to download it.

**Comment by r2dr0dn** [comment]
**yd-dlc** Cannot Fetch (In General Private Videos), it requires authentications, although in this case **yd-dlc** possibly cannot authenticate with fb even with specifying (username,password) probably because it's doesn't support fb auth .
You'll have to make the video publicly accessible in order to download then switch back to private .

**Comment by digital-pet** [comment]
> 
> 
> **yd-dlc** Cannot Fetch (In General Private Videos), it requires authentications, although in this case **yd-dlc** possibly cannot authenticate with fb even with specifying (username,password) probably because it's doesn't support fb auth .
> You'll have to make the video publicly accessible in order to download then switch back to private .

It successfully authenticates in the verbose log shared above, and entering an incorrect password causes it to fail to login. This is not an account with 2FA installed, which is the only situation where facebook auth is not supported to my knowledge unless there has been a regression in yt-dlc

**Comment by digital-pet** [comment]
#52

This appears related to this issue which i missed on my initial search, hopefully that fix gets merged soon!
