### ISSUE TITLE
[Question] How to save video titles or URLs alongside the IDs when using (download archive)?

### ISSUE THREAD

**Issue by 54m4d** [blackjack4494/yt-dlc#257]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Hi! 👋

When using `--download-archive` function youtube-dl saves the video `IDs` to a .txt file. How can i add video `titles`/`URLs` to it so that it becomes something like this:

```
Ducks having a conversation
youtube xJVwvq5z3MI
```

OR:

```
Ducks having a conversation
https://www.youtube.com/watch?v=xJVwvq5z3MI
```
Or if there's any other way to save the `title`+`IDs`/`URLs` together in a text file with no more info than that?

**Comment by pukkandan** [comment]
--download-archive is not meant as a method to save information, but only to prevent the same videos from being redownloaded.
If you want to download the titles as well, you can seperately use `--get-title` like this:

``` bash
# First save titles
youtube-dlc --get-title --download-archive archivefile URL > titles.txt
# Then download
youtube-dlc --download-archive archivefile URL
```

**Comment by fosam** [comment]
@pukkandan Thanks for your suggestion.
> ```shell
> # First save titles
> youtube-dlc --get-title --download-archive archivefile URL > titles.txt
> ```

This first part did not work for me, what does this suppose to do?

Can we please apply that example on this [channel?](https://www.youtube.com/channel/UCRORnIfELvclyrfTvl4dLTg)

I want to save both the `titles` and video `IDs`/`URLs` in a separate txt file

**Comment by pukkandan** [comment]
> This first part did not work for me, what does this suppose to do?

It saves the titles in the file "titles.txt". Getting both URL and title in one file is a bit tricky to do. ID and title can be done more easily.

`youtube-dl.cmd --get-filename -o "%(id)s %(title)s" https://www.youtube.com/channel/UCRORnIfELvclyrfTvl4dLTg >>titles.txt` will give you:

```
luTsCwtR6GU Bunny Binky in slow motion
dlVapXhl9rU bunny can't stop licking me
qs3G4JWEGvo Watch this antelope eat out of my hand!
_TIpKO8pqiY Watch this dog freak out!
VKpn1tGa9zE Have you ever seen a baby bunny sneeze
9656FFjLrmg Call of Duty  - Modern Warfare Remastered best 1v1 ever
```

**Comment by fosam** [comment]
Now i know what i did wrong:

I tried with `--download-archive titles.txt` insted of the right one `>>titles.txt` now this recorded both the IDs and titles in the txt file

But in the first example you provided: `--download-archive archivefile URL > titles.txt` what was this for?

**Comment by pukkandan** [comment]
`--download-archive archive.txt` creates the archive `archive.txt`; ie, it prevents the same video from being downloaded multiple times.
`>>titles.txt` appends the output of `--get-filename` to titles.txt. You can use either or both according to your needs.

**Comment by fosam** [comment]
@pukkandan Thanks!

Where can i learn more about the `>>titels.txt`? i couldn't find anything on the documentaion

**Comment by fosam** [comment]
> `>>titles.txt` appends the output of `--get-filename` to titles.txt. You can use either or both according to your needs.

@pukkandan 

Also why did you use `--get-filename`? shouldn't that be `--get-title` instead since we're looking for titles and not filenames?

I'm very confused, please help

**Comment by Vangelis66** [comment]
@fosam wrote

> I never heard of `>>` option

... This isn't a `yt-dlc` specific option, but a system one;. please read on [redirection operators](https://www.lifewire.com/redirection-operator-2625979) ... :smile:

**Comment by fosam** [comment]
Just read it, Thanks @Vangelis66

**Comment by pukkandan** [comment]
> Also why did you use --get-filename? shouldn't that be --get-title instead since we're looking for titles and not filenames?

It is a hack to get id and title together. `--get-title` will only give you the `title` and not the `id`.
`--get-filename -o "%(id)s %(title)s"` tells yt-dlc to name the file as `id title` and then print that title. That way we get both id and title in a single command
