### ISSUE TITLE
[Broken] Newgrounds

### ISSUE THREAD

**Issue by mon5termatt** [blackjack4494/yt-dlc#27]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dlc version **2020.10.26**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
D:\`user`\Documents\Youtube-DL>youtube-dlc https://www.newgrounds.com/portal/view/769705 -v
[debug] System config: []
[debug] User config: ['-o', 'F:/Videos/Downloaded/%(title)s.%(ext)s', '--write-sub', '--write-auto-sub']
[debug] Custom config: []
[debug] Command-line args: ['https://www.newgrounds.com/portal/view/769705', '-v']
[debug] Loading archive file None
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dlc version 2020.10.26
[debug] Python version 3.8.6 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg git-2020-04-03-52523b6, ffprobe git-2020-04-03-52523b6
[debug] Proxy map: {}
[Newgrounds] 769705: Downloading webpage
ERROR: Unable to extract ; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dlc -U  to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dlc\YoutubeDL.py", line 830, in extract_info
  File "youtube_dlc\extractor\common.py", line 532, in extract
  File "youtube_dlc\extractor\newgrounds.py", line 64, in _real_extract
  File "youtube_dlc\extractor\common.py", line 1010, in _search_regex
youtube_dlc.utils.RegexNotFoundError: Unable to extract ; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dlc -U  to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
```

## Description

fails to download from newgrounds. using a random video for this example but have tried on multiple.

# PLEASE LET ME KNOW IF YOU NEED MORE INFO

**Comment by october262** [comment]
1st - play the  video - https://www.newgrounds.com/portal/view/769705
2nd - hit F12 to bring up the debug menu screen, choose network - media.
the first info line, under Type says media it is the mp4, copy the link address and feed it into youtube-dlc.

**Comment by blackjack4494** [comment]
Sometimes regex changes. That can be a url with new structure or when the video is linked/embedded into the html the position might change.  
If on Chrome you can also use `Ctrl + U`, right click to view source or type `view-source:url` in front of your url. Then you could use search to find '.mp4' or 'dash, manifest, m3u8, mpd'

**Comment by mon5termatt** [comment]
Alright thanks for the fix. Is there any possible way this could be improved /enhanced in the future so all you have to input is the url or would that be impossible

**Comment by mon5termatt** [comment]
Wanted to say thanks. Was able to download an entire users videos last night!
