### ISSUE TITLE
Auto-translate subs not being scraped from YouTube

### ISSUE THREAD

**Issue by michealespinola** [blackjack4494/yt-dlc#271]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dlc version **2020.11.11-3**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
C:\Scripts>youtube-dlc --write-auto-sub  https://www.youtube.com/watch?v=XAqfFLtARZI
[debug] System config: []
[debug] User config: ['--verbose', '--sub-lang', 'en,EN,en-gb,en-GB,EN-GB,en-ca,en-CA,EN-CA,en-ie,en-IE,EN-IE,en-us,en-US,EN-US,eng,ENG,english,English,ENGLISH,subtitles', '--write-sub', '--write-auto-sub', '--write-thumbnail', '--write-all-thumbnails', '--embed-thumbnail', '--write-description', '--write-info-json', '--add-metadata', '--xattrs', '--ignore-errors', '--no-playlist', '--format', '(bestvideo+bestaudio/bestvideo)[protocol!*=m3u8]/bestvideo+bestaudio/best', '--batch-file', 'C:/Users/USERNAME/AppData/Roaming/youtube-dl/download-queue.txt', '--force-ipv4', '--cookies', 'C:/Users/USERNAME/common-info/cookies.txt', '--no-check-certificate', '--user-agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36', '--abort-on-unavailable-fragment', '--socket-timeout', '30', '--retries', '999', '--hls-prefer-native', '--merge-output-format', 'mkv', '--audio-quality', '0', '--cache-dir', 'C:/Users/USERNAME/AppData/Roaming/youtube-dl/cache', '--restrict-filenames', '--no-mtime', '--output', 'D:/Downloads/youtube-dl/%(extractor)s/%(title)s [%(resolution)s] [%(id)s] [f%(format_id)s].%(ext)s']
[debug] Custom config: []
[debug] Command-line args: ['--write-auto-sub', 'https://www.youtube.com/watch?v=XAqfFLtARZI']
[debug] Batch file urls: []
[debug] Loading archive file None
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dlc version 2020.11.11-3
[debug] Python version 3.8.6 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 4.3, ffprobe 4.3, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] XAqfFLtARZI: Downloading webpage
[youtube] Downloading just video XAqfFLtARZI because of --no-playlist
[youtube] XAqfFLtARZI: Looking for automatic captions
WARNING: Couldn't find automatic captions for XAqfFLtARZI
[...]
```

## Description

Auto-translated subs (via '`--write-auto-sub`') are not downloaded from YouTube. As a comparison, this function works properly in youtube-dl 2020.11.29. This is also apparent when using the '`--list-subs`' option, where youtube-dlc will respond for the example video with '`WARNING: Couldn't find automatic captions for XAqfFLtARZI`', but youtube-dl will respond with a list of 109 possible auto-translations.

**Comment by blackjack4494** [comment]
I see the problem. `json3` format is the problem. Depending on the order/position in this list `_SUBTITLE_FORMATS = ('srv1', 'srv2', 'srv3', 'ttml', 'json3', 'vtt')` automatic captions will be found or not.

**Comment by michealespinola** [comment]
Thank you very much!

**Comment by nicolaasjan** [comment]
@blackjack4494 @michealespinola 
Seems to be resolved with [this commit](https://github.com/ytdl-org/youtube-dl/commit/4ef1fc970727a1bbdd9f20bea54c37deb8794fb0) from upstream.
