### ISSUE TITLE
[Broken] NBC - ERROR: Unable to download webpage: HTTP Error 400: Bad Request

### ISSUE THREAD

**Issue by StevenDTX** [blackjack4494/yt-dlc#278]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dlc version **2020.11.11-3**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
U:\>c:\support\youtube-dlc.exe --verbose --ap-mso Charter_Direct --ap-username <username> --ap-password <password> "https://www.nbc.com/below-deck/video/champagne-wishes-and-caviar-screams/4272148"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--ap-mso', 'Charter_Direct', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', 'https://www.nbc.com/below-deck/video/champagne-wishes-and-caviar-screams/4272148']
[debug] Loading archive file None
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dlc version 2020.11.11-3
[debug] Python version 3.8.6 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg N-92986-gaceb9131c1, ffprobe N-92986-gaceb9131c1
[debug] Proxy map: {}
[NBC] 4272148: Downloading JSON metadata
[NBC] 4272148: Downloading Provider Redirect Page
ERROR: Unable to download webpage: HTTP Error 400: Bad Request (caused by <HTTPError 400: 'Bad Request'>); please report this issue on https://github.com/blackjack4494/yt-dlc . Make sure you are using the latest version; type  youtube-dlc -U  to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
  File "youtube_dlc\extractor\common.py", line 632, in _request_webpage
  File "youtube_dlc\YoutubeDL.py", line 2316, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
```

## Description
Unable to extract video id.

This affects ALL of the NBC network sites:
https://www.nbc.com/networks/oxygen
https://www.nbc.com/networks/cnbc
https://www.nbc.com/networks/e
https://www.nbc.com/networks/usa
https://www.nbc.com/networks/bravo

**Comment by glubsy** [comment]
I can confirm I'm getting the same error on Youtube video as well.

**Comment by keith-leitch** [comment]
All seems fine to me. I just downloaded SNL and Transplant. Admittedly, I can't download your link, but that seems to be (according to the error) because I don't have a TV provider.

**Comment by StevenDTX** [comment]
It turns out, that NBC no longer supports Charter_Direct as an MSO, and neither youtube-dlc or youtube-dl supports Spectrum as an MSO.  This works just fine with other MSOs, like DTV.
