### ISSUE TITLE
Is this legal???

### ISSUE THREAD

**Issue by abhi1693** [blackjack4494/yt-dlc#284]

**Comment by Meowx3** [comment]
Yes it is, at least in the USA. I can't speak for other countries but I imagine it would be in most. It is simply a tool that allows you to archive and save content that is already available to you legitimately using streaming playlists shared by the media hosts. While it requires understanding the coding, you could do exactly the same without this tool easily yourself by just using your browsers "View Code" option. This action is what your browser is automatically doing when you view content online, it is just not deleting when the cache is cleared. Where things get murky is in how the user decides to use the content as all original copyrights and such must still be honored. It could be a violation of TOS for various services as any service provider can set their own TOS however they wish (without infringing on laws or rights) so the services would be in the right to disallow you to continue to accessing their content if they chose to.
