### ISSUE TITLE
[Broken]YT playlist - collected 0 ids

### ISSUE THREAD

**Issue by someziggyman** [blackjack4494/yt-dlc#33]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dlc version **2020.10.26**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
ytdlc -v -F https://youtu.be/-gJaYKwreEc?list=RD-gJaYKwreEc
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'https://youtu.be/-gJaYKwreEc?list=RD-gJaYKwreEc']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.09.20
[debug] Python version 2.7.16 (CPython) - Darwin-19.6.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[youtube:playlist] Downloading playlist RD-gJaYKwreEc - add --no-playlist to just download video -gJaYKwreEc
[youtube:playlist] RD-gJaYKwreEc: Downloading page 1 of Youtube mix
[download] Downloading playlist: RD-gJaYKwreEc
[youtube:playlist] playlist RD-gJaYKwreEc: Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: RD-gJaYKwreEc
```

## Description

test links:
https://www.youtube.com/watch?v=-gJaYKwreEc&feature=youtu.be&list=RD-gJaYKwreEc

https://youtu.be/-gJaYKwreEc?list=RD-gJaYKwreEc

Tried some other playlists and they seem to be fine.

Assume this could be a formatting problem of the initial link.
Opened that channel, navigated to playlists and took this link for that very same playlist wanted initially:
https://www.youtube.com/watch?v=-gJaYKwreEc&list=PLF-k_OIEn_PMQ4bYJGD1Jx1OUAM7zwaEH
It works. 
Please take a look and in case this is just a link formatting problem, just close this issue.

**Comment by merval** [comment]
I was looking at this code this morning. There is a weird situation where an error isn't caught but it continues on as if everything is fine. Not sure what the story there is. Hopefully I can find some time today to look deeper.

**Comment by insaneracist** [comment]
The playlist that you wanted, and that worked (list id starting with PL), is not the same thing as the first links (list id starting with RD and then same id as video). That was a youtube mix, which is a list of videos youtube thinks are related, not a playlist proper. 

Youtube mix downloading is breaking [here](https://github.com/blackjack4494/yt-dlc/blob/ddb77f30ee597aa5d23079fe6654b7e2e4a91656/youtube_dlc/extractor/youtube.py#L2777-L2780) because it's looking for data in an html attribute, that, at least for the versions the pages that youtube sends me, has been moved into json

**Comment by blackjack4494** [comment]
The code for ytsearch is reusable if slightly modified for those new feeds.

**Comment by pgenderson** [comment]
Doesn't work for me either:

```
$ youtube-dlc -x RDKobbM94mXbo
[youtube:playlist] RDKobbM94mXbo: Downloading page 1 of Youtube mix
[download] Downloading playlist: RDKobbM94mXbo
[youtube:playlist] playlist RDKobbM94mXbo: Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: RDKobbM94mXbo
```

**Comment by leodomi** [comment]
I have the same problem with the "Collected 0 video ids"

**Comment by someziggyman** [comment]
I found a curios YT Mix playlist that still has this **Collected 0 video ids** 
https://www.youtube.com/playlist?list=RDCMUCGZ0LgTmAJn9Banetdr_ZFg

got it from here:
https://www.youtube.com/watch?v=_OgBDRPoIcA&list=RDCMUCGZ0LgTmAJn9Banetdr_ZFg&start_radio=1&t=0

[youtube:playlist] RDCMUCGZ0LgTmAJn9Banetdr_ZFg: Downloading page 1 of Youtube mix
[download] Downloading playlist: RDCMUCGZ0LgTmAJn9Banetdr_ZFg
[youtube:playlist] playlist RDCMUCGZ0LgTmAJn9Banetdr_ZFg: Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: RDCMUCGZ0LgTmAJn9Banetdr_ZFg

**Comment by insaneracist** [comment]
great find, looks like `RDCM` is prefix for a mix based on channel id rather than video id, `UCGZ0LgTmAJn9Banetdr_ZFg` and `UCmvAV_za1KXGXSgC0o0v9DQ` are the channels
