### ISSUE TITLE
[Question] How do i get the Video Title (aka the default output filename) as a variable in Python?

### ISSUE THREAD

**Issue by FlyingThunder** [blackjack4494/yt-dlc#34]
## Checklist

- [x ] I'm asking a question
- [x ] I've looked through the README and FAQ for similar questions
- [x ] I've searched the bugtracker for similar questions including closed ones

I want to download a video and give the user the option to keep the video for later, but for further processing i need to somehow store the output file name as a variable, i cant find any way to do so, and i dont want to make a big workaround by using `os` to check the file manually

EDIT: I am aware of the `extract_info` option, but this wont give me the literal file name, as it ommits e.g. `:` and turns it into `-`

**Comment by insaneracist** [comment]
assuming you have something like
```python
ydl = youtube_dlc.YoutubeDL()
info_dict = ydl.extract_info('https://www.youtube.com/watch?v=...', download=False)
```
you can do 
```python
ydl.prepare_filename(info_dict)
```
