### ISSUE TITLE
[Question] Migrate to Codeberg

### ISSUE THREAD

**Issue by varbhat** [blackjack4494/yt-dlc#5]
## Checklist

- [ x] I'm asking a question
- [x ] I've looked through the README and FAQ for similar questions
- [ x] I've searched the bugtracker for similar questions including closed ones

## Question

I think that This project can be migrated to https://codeberg.org or other Open Source friendly Git hosting service.

**Comment by CatTheHacker** [comment]
And how is GitHub not open source friendly?

**Comment by blackjack4494** [comment]
I actually plan to mirror the code on multiple sites. Also there are plans on moving away from Github.

**Comment by CatTheHacker** [comment]
> Github is. But as they are US company they will just quickly comply with DMCA takedowns whether really justified or not. Everyone can file a complain as long as their rights are somehow hurt.

I know, I'm just little hurt whenever someone says it's GitHub fault when it's not :)

**Comment by varbhat** [comment]
> And how is GitHub not open source friendly?

It's debatable.

I think that Github is not good home for project like yt-dlc .

**Comment by theincognito-inc** [comment]
@blackjack4494 Whatever git service you choose, please let us know!!

**Comment by ohnonot** [comment]
> I actually plan to mirror the code on multiple sites. Also there are plans on moving away from Github.
> 
> Github is. But as they are US company they will just quickly comply with DMCA takedowns whether really justified or not. Everyone can file a complain as long as their rights are somehow hurt.

Woohoo!
I hope this will include issues & communication?
I believe gitlab can mirror those as well?
FWIW, I use [url=https://framagit.org/]framagit[/url] (gitlab based) and [url=https://notabug.org/]notabug[/url].
