### ISSUE TITLE
[Broken] Youtube sometimes fails with "Unable to extract video data" for the same video.

### ISSUE THREAD

**Issue by peet1993** [blackjack4494/yt-dlc#56]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dlc version **2020.10.26**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: [] 
[debug] User config: []
[debug] Custom config: [] 
[debug] Command-line args: [u'--no-warnings', u'--dump-json', u'--verbose', u'--id', u'--', u'6-8E4Nirh9s'] 
[debug] Loading archive file None 
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8 
[debug] youtube-dlc version 2020.10.25 [debug] Python version 2.7.16 (CPython) - Linux-4.19.0-10-amd64-x86_64-with-debian-10.6 
[debug] exe versions: ffmpeg 4.1.6-1, ffprobe 4.1.6-1 
[debug] Proxy map: {} ERROR: 6-8E4Nirh9s: YouTube said: Unable to extract video data
Traceback (most recent call last): 
File "./youtube-dlc/youtube_dlc/YoutubeDL.py", line 830, in extract_info ie_result = ie.extract(url) 
File "./youtube-dlc/youtube_dlc/extractor/common.py", line 532, in extract ie_result = self._real_extract(url) 
File "./youtube-dlc/youtube_dlc/extractor/youtube.py", line 1866, in _real_extract 'YouTube said: %s' % unavailable_message, expected=True, video_id=video_id) 
ExtractorError: 6-8E4Nirh9s: YouTube said: Unable to extract video data

```

## Description

Currently, about 3% of video analysis for youtube fails with "Unable to extract video data", even when always using the same URL. The problem ist that sometimes Youtube delivers a player page which does not contain the expected "args": "player_response" object (see youtube.py - _real_extract()).

I did not have time to investigate further today, therefore I open this issue for others to investigate. I will update this if I find out more, if someone else finds something, please add to this issue :)

I attached a working and a non-working reponse to this issue for further investigation.
[responses.zip](https://github.com/blackjack4494/yt-dlc/files/5461725/responses.zip)

**Comment by peet1993** [comment]
Where does the 3% come from? I wrote a script analysing the same URL over and over again (to get a broken example originally):
```
./check_extract_bug.sh 
Success rate: 96.53% (195/202)
```

I previously ran it for 2000 tries, landing at about the same percentage.

**Comment by insaneracist** [comment]
Interesting, looks like the same `player_response` object is there in fail.html, it is called `ytInitialPlayerResponse` instead

**Comment by yhtojy** [comment]
I have this same issue with my account on probably all Youtube links.
The response will always send it back as the fail.html one.
If I use another account, maybe it will like @peet1993 said. It is 3%.

(Both account using same Youtube settings)

> C:\Users\JamesW>"D:\Data\YoutubeDownloader\youtube-dlc.exe" --cookies=newcookiefile.txt https://www.youtube.com/watch?v=ZWXVI11ZLPk -v --write-page
> [debug] System config: []
> [debug] User config: ['-o', 'D:/Data/YoutubeDownloader/DL/%(title)s.%(ext)s']
> [debug] Custom config: []
> [debug] Command-line args: ['--cookies=newcookiefile.txt', 'https://www.youtube.com/watch?v=ZWXVI11ZLPk', '-v', '--write-page']
> [debug] Loading archive file None
> [debug] Encodings: locale cp950, fs utf-8, out utf-8, pref cp950
> [debug] youtube-dlc version 2020.10.25
> [debug] Python version 3.8.6 (CPython) - Windows-10-10.0.18362-SP0
> [debug] exe versions: ffmpeg 4.3.1-2020-10-01-full_build-www.gyan.dev, ffprobe 4.3.1-2020-10-01-full_build-www.gyan.dev
> [debug] Proxy map: {}
> [youtube] ZWXVI11ZLPk: Downloading webpage
> [youtube] Saving request to ZWXVI11ZLPk_https_-_www.youtube.com_watchv=ZWXVI11ZLPk_gl=US_hl=en_has_verified=1_bpctr=9999999999_disable_polymer=true.dump
> ERROR: ZWXVI11ZLPk: YouTube said: Unable to extract video data
> Traceback (most recent call last):
>   File "youtube_dlc\YoutubeDL.py", line 830, in extract_info
>   File "youtube_dlc\extractor\common.py", line 532, in extract
>   File "youtube_dlc\extractor\youtube.py", line 1865, in _real_extract
> youtube_dlc.utils.ExtractorError: ZWXVI11ZLPk: YouTube said: Unable to extract video data

youtube-dlc.exe build from today. https://github.com/blackjack4494/yt-dlc/tree/4932ba4aecf653166f04211680a48624b48f030f

[ZWXVI11ZLPk_https_-_www.youtube.com_watchv=ZWXVI11ZLPk_gl=US_hl=en_has_verified=1_bpctr=9999999999_disable_polymer=true.txt](https://github.com/blackjack4494/yt-dlc/files/5463068/ZWXVI11ZLPk_https_-_www.youtube.com_watchv.ZWXVI11ZLPk_gl.US_hl.en_has_verified.1_bpctr.9999999999_disable_polymer.true.txt)

**Comment by simpleperson123** [comment]
> Where does the 3% come from? I wrote a script analysing the same URL over and over again (to get a broken example originally):
> 
> ```
> ./check_extract_bug.sh 
> Success rate: 96.53% (195/202)
> ```
> 
> I previously ran it for 2000 tries, landing at about the same percentage.

I heard that Youtube is testing new version of its player. Sometimes it's served instead of the standard player that works with yt-dlc.

**Comment by abayochocoball** [comment]
Took a closer look at this issue. Youtube is serving different page response depending on your account (and it appears on some videos at random), they are probably testing a new page. 

youtube._get_ytplayer_config searches for the ytconfig_section from the webpage using the following regex patterns
```
            r';ytplayer\.config\s*=\s*({.+?});ytplayer',
            r';ytplayer\.config\s*=\s*({.+?});',
```
neither of these two will find anything in the new response.

using `r'ytInitialPlayerResponse\s*=\s*({.+?});var meta'` I was able to extract something resembling `player_response` from the old pages.

Old Page
```
<script >var ytplayer = ytplayer || {};ytplayer.config = {"args":{"player_response":"{\"responseContext\":{\"serviceTrackingParams\":...{\"serializedSlotAdServingDataEntry\":\"\"}}}]}"}};ytplayer.web_player_context_config
```
New Page
```
<script nonce="yQgGLM0ZubpmF+JbvjNyLQ">var ytInitialData = {"responseContext"..."adSlotLoggingData": {..."serializedSlotAdServingDataEntry": ""}}}]};var meta = document.createElemen
```

As for using the new format, I'm not sure where to get the info that would have previously been associated with ytplayer_config['args'], but ignoring that section and using the matched string returned from `_get_ytplayer_config` as `player_response` successfully downloaded a video while using cookies to log into an account that was being served the new webpage.

**Comment by nicolaasjan** [comment]
@peet1993 
Just FYI, maybe you should use `python3` (not particularly for this issue).
I have an alias for that in `.bash_aliases` (is in your /home folder; if not, create it).
`alias youtube-dlc='python3 /usr/local/bin/youtube-dlc'`

**Comment by peet1993** [comment]
@abayochocoball Wow perfect, thank you :) I checked the complete output of the new ytInitialPlayerResponse vs the old player_response (with a diff-tool) and it does not only resemble the old one, its (almost) exactly the same!

The only other usage of `_get_ytplayer_config()` is in `_get_automatic_captions()`:
![image](https://user-images.githubusercontent.com/19955832/97761644-89c3db00-1b06-11eb-999a-1d7db32914bc.png)

I applied your part of the fix, then continued to fix the automatic caption extraction. It works perfectly :+1: 
```
./check_extract_bug.sh
Success rate: 100.00% (320/320), Captions: 32/288/0, Video: 32/288/0
```
The 3 numbers are "old player"/"new player"/"some other method". Seems like YouTube picked up the pace since yesterday, now its 10% of the calls using the new player.

I opened a pull request with the fix, feel free to comment: #68

**Comment by peet1993** [comment]
> @peet1993
> Just FYI, maybe you should use `python3` (not particularly for this issue).
> I have an alias for that in `.bash_aliases` (is in your /home folder; if not, create it).
> `alias youtube-dlc='python3 /usr/local/bin/youtube-dlc'`

Thanks for the hint, I usually use python3, it seems I had my IDE configured incorrectly :sweat_smile:

**Comment by blackjack4494** [comment]
Well it should be fixed with next release. At least for me the newest version is working. Will let this open for some days.

**Comment by peet1993** [comment]
I cannot confirm that this is fixed with the current release 2020.10.31 and also not on the current master.
```
./check_extract_bug.sh 
Success rate: 93.10% (54/58)
```
Note that this is a different problem the JS player fixed in #35.

**Comment by marabu88** [comment]
I'm sorry, is this the same problem? Some pages containing licensed music have been changed so that the old version of the program stops working with them?

`ERROR: Unable to extract JS player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dlc -U  to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.`

**Comment by peet1993** [comment]
Are you running the newest version 2020.10.31? This is not the same and should be fixed.

**Comment by marabu88** [comment]
> Are you running the newest version 2020.10.31? This is not the same and should be fixed.

I thought I had the latest version. I downloaded a new version, everything works fine. Excuse me.

**Comment by happysmash27** [comment]
I literally just installed it (via pip) and it failed on a video with the same error.

**Comment by HashLiver** [comment]
v2020.10.31 happening again, I tried **8** times, same command and finally successfully downloaded
```
youtube-dlc -v https://www.youtube.com/watch?v=7VSR4_tAYvw
[debug] System config: []
[debug] User config: ['--proxy', '127.0.0.1:1080', '-f', 'bestvideo[height<=1080][fps<=30][vcodec=vp9]+bestaudio/best', '--merge-output-format', 'mkv', '--write-sub', '--sub-lang', 'zh-CN,zh-TW,en,ja', '--convert-subs', 'srt', '--embed-subs', '--add-metadata', '-o', 'F:\\%(title)s.%(ext)s', '--user-agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=7VSR4_tAYvw']
[debug] Loading archive file None
[debug] Encodings: locale cp936, fs utf-8, out utf-8, pref cp936
[debug] youtube-dlc version 2020.10.31
[debug] Python version 3.9.0 (CPython) - Windows-10-10.0.18362-SP0
[debug] exe versions: ffmpeg git-2020-08-31-4a11a6f, ffprobe git-2020-08-31-4a11a6f
[debug] Proxy map: {'http': '127.0.0.1:1080', 'https': '127.0.0.1:1080'}
[youtube] 7VSR4_tAYvw: Downloading webpage
ERROR: 7VSR4_tAYvw: YouTube said: Unable to extract video data
Traceback (most recent call last):
  File "youtube_dlc\YoutubeDL.py", line 830, in extract_info
  File "youtube_dlc\extractor\common.py", line 532, in extract
  File "youtube_dlc\extractor\youtube.py", line 1903, in _real_extract
youtube_dlc.utils.ExtractorError: 7VSR4_tAYvw: YouTube said: Unable to extract video data
```
