### ISSUE TITLE
[Feature Request] How to host yt-dlc offshore without risk of it getting taken down

### ISSUE THREAD

**Issue by FrickTheRIAA** [blackjack4494/yt-dlc#59]
Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dlc version **2020.10.26**
- [x] I've searched the bugtracker for similar feature requests including closed ones

I have put together a guide on how to host yt-dlc offshore using companies that have a track record of being very resilient to DMCA takedowns: https://old.reddit.com/r/youtubedl/comments/jktx5b/how_to_anonymously_host_the_continued_development/
I won't copy paste the whole guide onto this issue ticket since it might be better to just link to it off-site and have further away from the development of the software.

**Comment by BlohoJo** [comment]
Your reddit post was removed.

**Comment by FrickTheRIAA** [comment]
@BlohoJo Yeah, it seems like it was removed. I left a comment about it in the thread, but that comment was instantly hidden. Feels a bit shitty, I put more time into this than I should have. I haven't broken any rules as far as I'm aware and nothing mentioned in my post is illegal. I basically wrote an almost 4000 word well-researched essay with citations and everything, so a sentence in return from whoever removed my thread (be it mods or Reddit themselves) doesn't seem like too much to ask.

Anyway, I've reuploaded it to Disroot's CryptPad. Good luck taking it down from there:
[Viewing mode](https://cryptpad.disroot.org/code/#/2/code/view/GcymuR0ll9qlGbYtCvI89Q6WxKTT0wvmboh4lnNt4rA/embed/present/) (text only)
[Markdown mode](https://cryptpad.disroot.org/code/#/2/code/view/GcymuR0ll9qlGbYtCvI89Q6WxKTT0wvmboh4lnNt4rA/embed/)

**Comment by FrickTheRIAA** [comment]
[A mod managed to restore the original Reddit thread](https://old.reddit.com/r/youtubedl/comments/jlnnzg/backup_of_how_to_anonymously_host_the_continued/gaqyinj/) and [confirmed that the thread was not removed by the /r/youtubedl mods](https://old.reddit.com/r/youtubedl/comments/jktx5b/how_to_anonymously_host_the_continued_development/#gao9ff2), which means that it was indeed removed by Reddit.
