### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by iainheng** [blackjack4494/yt-dlc#6]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Hi, I just installed `youtube-dlc` on my MacBook using `cURL` but for all the commands I made, I ended up with `syntax error near unexpected token 'newline'` as shown in screenshot below 

![image](https://user-images.githubusercontent.com/3263759/97071397-a184f600-1612-11eb-85d9-15ffdef2015a.png)

Is this a bug or anything I did wrong?

**Comment by po5** [comment]
The update function -U tries to access the latest release, it probably still points to the now DMCA'd repo.
You'll have to manually update the binary, will be dealt with when all this mess is sorted out.

**Comment by merval** [comment]
Hmm. This might be the issue:
https://github.com/blackjack4494/yt-dlc/blob/dd2d55f10dac8b6cb5e8ab4b2cccb302655b40ea/youtube_dlc/update.py#L35

Let me do some testing and see what I get.

**Comment by merval** [comment]
Hm, I pulled down the code, built it and tried updating, but I get a different message that it couldn't find the current version. The corrected URL 'https://blackjack4494.github.io/update/' doesn't point anywhere, so that's the problem The update process is broken. I'm not familiar enough with Github to know how that's suppose work.

**Comment by merval** [comment]
The original code pointed to 'https://yt-dl.org/update/' which was a redirect to 'https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl'
The original code looks like this:
`
UPDATE_URL = 'https://yt-dl.org/update/'
VERSION_URL = UPDATE_URL + 'LATEST_VERSION'
JSON_URL = UPDATE_URL + 'versions.json'
`
After snooping at the redirects, it gathers the VERSION_URL like this, 'https://ytdl-org.github.io/youtube-dl/update/LATEST_VERSION'
Thanks to the wayback machine you can see where ytdl-org.github.io/youtube-dl looked like: https://web.archive.org/web/20201018143534/https://ytdl-org.github.io/youtube-dl/
The /update/version.json is specific to that page, likely updated when a new version was released.
So for now, the best way to actually update is to manually pull down released version.
