### ISSUE TITLE
[Question] Unit Tests failing, should we be fixing them?

### ISSUE THREAD

**Issue by merval** [blackjack4494/yt-dlc#63]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

While testing code changes, I noticed many of the unit tests are failing either due to unsupported URLs, timeouts or extractor errors. These are things we should be correcting, right? I didn't want to start down the path of looking at them if we don't intend on fixing them :-)

**Comment by blackjack4494** [comment]
Unfortunately the amount of work is just too much. I have exluded those tests in Travis. It would probably be better to write a new test program that only tests specific extractors instead of all.
