### ISSUE TITLE
[Broken] Unable to download Age Restricted videos on Youtube

### ISSUE THREAD

**Issue by BlueZonda** [blackjack4494/yt-dlc#66]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dlc version **2020.10.26**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[youtube] 1234567890: Downloading webpage
[youtube] 1234567890: Downloading embed webpage
[youtube] 1234567890: Refetching age-gated info webpage
Traceback (most recent call last):
  File "youtube_dlc\__main__.py", line 19, in <module>
  File "youtube_dlc\__init__.py", line 487, in main
  File "youtube_dlc\__init__.py", line 477, in _real_main
  File "youtube_dlc\YoutubeDL.py", line 2095, in download
  File "youtube_dlc\YoutubeDL.py", line 830, in extract_info
  File "youtube_dlc\extractor\common.py", line 532, in extract
  File "youtube_dlc\extractor\youtube.py", line 2068, in _real_extract
  File "json\__init__.py", line 341, in loads
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
[22460] Failed to execute script __main__
```

## Description

Using Windows version, I get this error while trying to download age restricted videos. It used to download properly till 2 days ago.

**Comment by peet1993** [comment]
Can you provide the video URL?

**Comment by BlueZonda** [comment]
I've just tried with other age restricted videos, it downloads, but somehow with the following video, it does not:
https://www.youtube.com/watch?v=p9r1Cw_LZ9g

**Comment by peet1993** [comment]
It works in the current version of this git repository (manually compiled). I suspect that it has something to do with #35.

**Comment by BlueZonda** [comment]
Can you provide me your manually compiled Windows exe?

**Comment by peet1993** [comment]
Sadly no, i'm on Linux :/

**Comment by BlueZonda** [comment]
I installed pyinstaller then youtube-dlc and followed these steps, which built me an EXE, it did not work.

> python -m pip install --upgrade pyinstaller
> pyinstaller.exe youtube_dlc\__main__.py --onefile --name youtube-dlc

What did I miss?

**Comment by GhostGuy9** [comment]
I'm having kind of the same issue but just says "YouTube said: Unable to extract video data"
