### ISSUE TITLE
Unable to extract JS player URL

### ISSUE THREAD

**Issue by numlockkey** [blackjack4494/yt-dlc#67]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dlc version **2020.10.26**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
youtube-dlc -v https://www.youtube.com/watch?v=rNlhTKTHgpo
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=rNlhTKTHgpo']
[debug] Loading archive file None
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dlc version 2020.10.26
[debug] Python version 3.8.6 (CPython) - Windows-10-10.0.18362-SP0
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1
[debug] Proxy map: {}
[youtube] rNlhTKTHgpo: Downloading webpage
[youtube] rNlhTKTHgpo: Downloading embed webpage
ERROR: Unable to extract JS player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dlc -U  to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dlc\YoutubeDL.py", line 830, in extract_info
  File "youtube_dlc\extractor\common.py", line 532, in extract
  File "youtube_dlc\extractor\youtube.py", line 2065, in _real_extract
  File "youtube_dlc\extractor\common.py", line 1010, in _search_regex
youtube_dlc.utils.RegexNotFoundError: Unable to extract JS player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dlc -U  to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.

```

## Description

Unable to extract JS player URL error

**Comment by greyboxgt** [comment]
I also see this often using version 2020.10.26, especially when using --cookies option and/or working within 65001 (UTF-8) code page (if I add chcp 65001 command).

**Comment by peet1993** [comment]
This is already fixed in #35 

Please search pull requests and closed tickets before opening a new issue :)

**Comment by filixm** [comment]
This is happening on many videos, vevo videos in particular. Started happening today.

**Comment by greyboxgt** [comment]
Not fixed here: https://github.com/blackjack4494/yt-dlc/releases/latest/download/youtube-dlc.exe
Please undersdand that not everybody can compile the code.

**Comment by peet1993** [comment]
> Not fixed here: https://github.com/blackjack4494/yt-dlc/releases/latest/download/youtube-dlc.exe
> Please undersdand that not everybody is able to compile the code.

I do absolutely understand that not everyone is able to compile code. But please understand the developers side of this: Getting new issues for already solved problems (that is just not released yet) causes overhead. Using the search is not a huge time investment, and the original ticket even has exactly the same name.

I'm sure there will be a release soon so that it works for everyone again! :)

**Comment by mat8913** [comment]
@greyboxgt You don't need to compile the code. Just run `python -m youtube_dlc https://www.youtube.com/watch?v=rNlhTKTHgpo` or whatever in the source directory.
