### ISSUE TITLE
[Question]How do I download age restricted video with youtube-dlc? youtube-dl is fine automatically

### ISSUE THREAD

**Issue by Klaus1189** [blackjack4494/yt-dlc#7]
I used youtube-dl many years and it automatically made it possible to download age restricted videos. 

But if I use youtube-dlc, it tells me:
ERROR: Video is age restricted and only playable on Youtube. Requires cookies!

How do I get the same automatically "cookie creation"?

Thanks in advance

**Comment by blackjack4494** [comment]
If it says so you need to provide your very own cookies. That is due the fact that some videos are only playable on youtube itself. There is a workaround in place to skip the need of cookies by using the embedded version but that is not working for on youtube only videos hence the need for cookies.

**Comment by nbmrjuhneibkr** [comment]
>There is a workaround in place

The workaround doesn't seem to be working in yt-dlc right now. All age-restricted videos can't be downloaded with yt-dlc, not just "YouTube-only" ones. Meanwhile, youtube-dl downloads such videos just fine.

**Comment by nbmrjuhneibkr** [comment]
Here is the commit that introduced this bug: https://github.com/blackjack4494/yt-dlc/commit/b492464bf125bd6c352bf4ab6dae1c38e5cb3c90

**Comment by october262** [comment]
> 
> 
> > There is a workaround in place
> 
> The workaround doesn't seem to be working in yt-dlc right now. All age-restricted videos can't be downloaded with yt-dlc, not just "YouTube-only" ones. Meanwhile, youtube-dl downloads such videos just fine.

this should be fixed in youtube-dlc

**Comment by nicolaasjan** [comment]
Works here...

But you _have_ to use the `--cookies.txt` option.

[Sidenote]
The example video you linked to (Justin Timberlake - Tunnel Vision), is one of the reasons of the DMCA take-down of the youtube-dl repo.
I don't think it's wise to mention it here...

**Comment by nbmrjuhneibkr** [comment]
> But you _have_ to use the `--cookies.txt` option.

No, you don't. I'll repeat: youtube-dl downloads age-restricted videos perfectly fine **without** cookies.txt. Only yt-dlc has this problem.

**Comment by Klaus1189** [comment]
> > But you _have_ to use the `--cookies.txt` option.
> 
> No, you don't. I'll repeat: youtube-dl downloads age-restricted videos perfectly fine **without** cookies.txt. Only yt-dlc has this problem.

Yes. I think now that it is indeed a bug.

How would I use the cookies.txt option for that? Documentation is down, do I need a new link?

**Comment by nicolaasjan** [comment]
> > But you _have_ to use the `--cookies.txt` option.
> 
> No, you don't. I'll repeat: youtube-dl downloads age-restricted videos perfectly fine **without** cookies.txt. Only yt-dlc has this problem.

The just use youtube-dl for those. ;)
I just meant, that with yt-dlc you must use this option (for now?).

**Comment by nbmrjuhneibkr** [comment]
`youtube-dl https://www.youtube.com/watch?v=7t0SqerlBA0 -f best`

Result:

```
[youtube] 7t0SqerlBA0: Downloading webpage
[youtube] 7t0SqerlBA0: Downloading embed webpage
[youtube] 7t0SqerlBA0: Refetching age-gated info webpage
[download] Destination: Test Age Restricted Video-7t0SqerlBA0.mp4
[download] 100% of 10.59MiB in 00:03
```
-----

`youtube-dl https://www.youtube.com/watch?v=7t0SqerlBA0 -f best`

Result:

```
[youtube] 7t0SqerlBA0: Downloading webpage
[youtube] 7t0SqerlBA0: Downloading embed webpage
ERROR: Video is age restricted and only playable on Youtube. Requires cookies!
```

**Comment by nicolaasjan** [comment]
> > > But you _have_ to use the `--cookies.txt` option.
> > 
> > 
> > No, you don't. I'll repeat: youtube-dl downloads age-restricted videos perfectly fine **without** cookies.txt. Only yt-dlc has this problem.
> 
> Yes. I think now that it is indeed a bug.
> 
> How would I use the cookies.txt option for that? Documentation is down, do I need a new link?

I explained [above](https://github.com/blackjack4494/yt-dlc/issues/7#issuecomment-716038621), Klaus.

**Comment by Klaus1189** [comment]
Thanks.

Hopefully this gets fixed

**Comment by blackjack4494** [comment]
@nbmrjuhneibkr you are partially right.  
Indeed the video you gave as an example is interesting.  
The way yt-dlc detecs whether you need cookies or not is by certain elements.  
I haven't seen a html structure like your example before.

To determine whether you can circumvent age gating the embedded version will be checked:
So yt-dlc checks for
`<div class="player-unavailable"><h1 class="message">`
which is also present in your video so it trigger the needs cookies warning
However this video also contains
`"playabilityStatus\":{\"status\":\"OK\"},\"videoFlags\":{\"playableInEmbed\":true,\"isCrawlable\":true,\"`
which wasn't the case with the normal working embedded ones and those who require youtube only and age.

So for instance try to download this video
https://www.youtube.com/watch?v=7takIh1nK0s
`<div class="player-unavailable"><h1 class="message">`
`\"playabilityStatus\":{\"status\":\"UNPLAYABLE\",\"reason\":\"Video nicht verfügbar\"},\"videoFlags\":{\"playableInEmbed\":false,\"isCrawlable\":true,\"`

So at least I know I should check for both playability Status and unavailable messages.

**Comment by nbmrjuhneibkr** [comment]
I don't think there's anything special about the example I provided. It behaves the same with every age-restricted video I could find.

**Comment by rubyFeedback** [comment]
Recently youtube-dl stopped working for me in regards to age-gate restricted videos.

I am almost 100% sure that this has to do with google changing things - guess they
don't like youtube-dl and variants.

**Comment by shakeyourbunny** [comment]
You need a VPN to appear to come from outside the European Union, then it works.

**Comment by shakeyourbunny** [comment]
https://www.digitalmusicnews.com/2020/11/02/youtube-age-gate-verification-europe/

Although this is an article from November 2020, they seem to have finally rolled it out for everyone there.

**Comment by pukkandan** [comment]
@rubyFeedback This repo has not had any updates for a while. You can try my fork [yt-dlp](https://github.com/yt-dlp/yt-dlp) where most age-gated content still works (not tested from EU)

**Comment by caniko** [comment]
> @rubyFeedback This repo has not had any updates for a while. You can try my fork [yt-dlp](https://github.com/yt-dlp/yt-dlp) where most age-gated content still works (not tested from EU)

Just tested in Germany, it works.

**Comment by aindriu80** [comment]
I got it to work with the following (cookies.txt by Lennon Hill) extension:-

https://addons.mozilla.org/en-US/firefox/addon/cookies-txt/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search

It adds an icon to the address bar, while on a youtube page click on the icon and export cookies.txt to the location you are running youtube-dl

Then type:

youtube-dl --cookies cookies.txt https://www.youtube.com/XYZ

♫♪.ılılıll|̲̅̅●̲̅̅|̲̅̅=̲̅̅|̲̅̅●̲̅̅|llılılı.♫♪

**Comment by tkwetzhy** [comment]
> Works here...
> 
> But you _have_ to use the `--cookies.txt` option.
> From the Readme (updated with recent links by me):
> 
> > ### How do I pass cookies to youtube-dl?
> > Use the `--cookies` option, for example `--cookies /path/to/cookies/file.txt`.
> > In order to extract cookies from browser use any conforming browser extension for exporting cookies. For example, [Get cookies.txt](https://chrome.google.com/webstore/detail/get-cookiestxt/bgaddhkoddajcdgocldbbfleckgcbcid) (for Chrome) or [cookies.txt](https://addons.mozilla.org/firefox/addon/cookies-txt/) (for Firefox).
> > Note that the cookies file must be in Mozilla/Netscape format and the first line of the cookies file must be either `# HTTP Cookie File` or `# Netscape HTTP Cookie File`. Make sure you have correct [newline format](https://en.wikipedia.org/wiki/Newline) in the cookies file and convert newlines if necessary to correspond with your OS, namely `CRLF` (`\r\n`) for Windows and `LF` (`\n`) for Unix and Unix-like systems (Linux, Mac OS, etc.). `HTTP Error 400: Bad Request` when using `--cookies` is a good sign of invalid newline format.
> > Passing cookies to youtube-dl is a good way to workaround login when a particular extractor does not implement it explicitly. Another use case is working around [CAPTCHA](https://en.wikipedia.org/wiki/CAPTCHA) some websites require you to solve in particular cases in order to get access (e.g. YouTube, CloudFlare).
> 
> [Side-note]
> The example video you linked to, is one of the reasons of the DMCA take-down of the youtube-dl repo.
> I don't think it's wise to mention it here...
> 
> Better replace it with a less high-profile link. ;)

It really works,thanks a lot!!

**Comment by nicolaasjan** [comment]
> It really works,thanks a lot!!

No problem!

In the mean time, note that this **yt-dlc** fork is no longer actively maintained.
You may want to try the **[yt-dlp](https://github.com/yt-dlp/yt-dlp)** fork instead.

**Comment by THGhost** [comment]
> > But you _have_ to use the `--cookies.txt` option.
> 
> No, you don't. I'll repeat: youtube-dl downloads age-restricted videos perfectly fine **without** cookies.txt. Only yt-dlc has this problem.

Can confirm that it does not. yt-dpl does though so all good there I guess.

**Comment by tkwetzhy** [comment]
> > It really works,thanks a lot!!
> 
> No problem!
> 
> In the mean time, note that this **yt-dlc** fork is no longer actively maintained. You may want to try the **[yt-dlp](https://github.com/yt-dlp/yt-dlp)** fork instead.

Thank you again!!!

**Comment by ValGadZ** [comment]
import subprocess
video_url = 'https://www.youtube.com/watch?v=HLuHxEzO3sE'
save_path = "airbourne.mp3"
command = f"yt-dlp --ffmpeg-location D:/Biggi/Trans/Mp3/ffmpeg-master-latest-win64-gpl-shared/bin/ffmpeg.exe --extract-audio --audio-format mp3 --audio-quality 192K {video_url} -o {save_path}"
subprocess.call(command, shell=True)
print("Downloaded successfuly.")

this helped me for mp3 download

[youtube] Extracting URL: https://www.youtube.com/watch?v=HLuHxEzO3sE
[youtube] HLuHxEzO3sE: Downloading webpage
[youtube] HLuHxEzO3sE: Downloading ios player API JSON
[youtube] HLuHxEzO3sE: Downloading android player API JSON
[youtube] HLuHxEzO3sE: Downloading m3u8 information
[info] HLuHxEzO3sE: Downloading 1 format(s): 251
[download] Destination: airbourne.webm
[download] 100% of   76.61MiB in 00:00:25 at 2.98MiB/s   
[ExtractAudio] Destination: airbourne.mp3
Deleting original file airbourne.webm (pass -k to keep)
Downloaded successfuly.

Process finished with exit code 0
