### ISSUE TITLE
[Question] Accuracy of VirusTotal report?

### ISSUE THREAD

**Issue by vonH** [blackjack4494/yt-dlc#71]
## Checklist

FAQ, etc. down due to suppression of FOSS.

- [X] I'm asking a question
- [X] I've looked through the README and FAQ for similar questions
- [X] I've searched the bugtracker for similar questions including closed ones

## Question

Is this report from VirusTotal accurate (https://www.virustotal.com/gui/file/763744714819c4a63ecda89e869eab4767e8d4304d544ff000298d267d198646/detection)
? The previous release did not have this issue.

Release scanned: youtube-dlc 2020.10.26 (youtube-dlc.exe). It looks like a false positive to me, but surprised to see it.

**Comment by nicolaasjan** [comment]
That report is for the previous version 2020.10.26.
[This one](https://www.virustotal.com/gui/file/05f0b669d5d0febccdb63505963562242f69e6e648deef5bb5bc934da8471bf6/detection) is for the newest version 2020.10.31.
It's however the same scanning engine "detecting" something, but it must be a false positive.

**Comment by ilike2burnthing** [comment]
One AI/ML detection (infamous for their false positives), and one relatively generic detection which changes between the two versions. The x86 executable has 3 AI/ML detections.

**Comment by blackjack4494** [comment]
That's due how pyinstaller is compiling/building the executable.  
There is some code or signature similar or equivalent to some known malicious code/executables.  
Maybe someone even used pyinstaller to compile their malicious code who knows.  

The whole code is open source and the process of compiling is public too. You could always build it yourself if you don't 'trust' certain sources. There is nothing someone can really do about. When it's some $$$ application, companies may ask the anti virus companies to whitelist their software.  

All you can do is either:
- build it yourself
- add it to exceptions
- don't use it

More information here 
https://stackoverflow.com/a/52054580/1515686

**Comment by fnordson** [comment]
> 
> 
> That's due how pyinstaller is compiling/building the executable.
> There is some code or signature similar or equivalent to some known malicious code/executables.
> Maybe someone even used pyinstaller to compile their malicious code who knows.

The Problem is: Windows Defender seems not to like it too since today...

![grafik](https://user-images.githubusercontent.com/5624605/99903276-bb723100-2cc3-11eb-9098-f7c51ba78765.png)

**Comment by nicolaasjan** [comment]
@fnordson

> The Problem is: Windows Defender seems not to like it too since today...

Windows Defender here (Windows 10 VM) doesn't complain at all (14:53)...
