### ISSUE TITLE
Viki not finding videos

### ISSUE THREAD

**Issue by pratherdude** [blackjack4494/yt-dlc#85]
I noticed that when I try to dl from viki with my script file it is no longer grabbing video files. I have updated both yt-dlc to 10.31.20 and pyhon. If you need more info please let me know, I don't have any programming experience so I'm not sure how to fix thisor if it's a change in Viki's website.

```$ bash download_archive.sh 
[debug] System config: []
[debug] User config: []
[debug] Custom config: ['-v', '-i', '-o', '/media/shaggy/Downloads/youtube-dl/%(playlist)s/%(title)s-%(season_number)s.%(episode_number)s-%(resolution)s.%(ext)s', '-u', 'PRIVATE', '-p', 'PRIVATE', '--add-header', 'x-viki-app-ver: 2.2.5.1428709186', '--add-header', 'x-viki-as-id: 100005a', '--socket-timeout', '30', '--rate-limit', '1048576', '--download-archive', 'youtube-dl-archive.txt', '-a', 'youtube-dl-channels.txt', '--max-downloads', '50', '--prefer-ffmpeg', '--merge-output-format', 'mkv', '--write-sub', '--sub-lang', 'en', '--sub-format', 'srt']
[debug] Command-line args: ['--config-location', 'youtube-dl.conf']
[debug] Adding header from command line option x-viki-app-ver: 2.2.5.1428709186
[debug] Adding header from command line option x-viki-as-id: 100005a
[debug] Batch file urls: ['https://www.viki.com/tv/32311c-strong-woman-do-bong-soon']
[debug] Loading archive file 'youtube-dl-archive.txt'
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dlc version 2020.10.31
[debug] Python version 3.8.5 (CPython) - Linux-5.4.0-52-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
[viki:channel] Logging in
[viki:channel] 32311c: Downloading channel JSON
[viki:channel] 32311c: Downloading episodes JSON page #1
[viki:channel] 32311c: Downloading clips JSON page #1
[viki:channel] 32311c: Downloading movies JSON page #1
[download] Downloading playlist: Strong Woman Do Bong Soon
[viki:channel] playlist Strong Woman Do Bong Soon: Collected 20 video ids (downloading 20 of them)
[download] Downloading video 1 of 20
[viki] Logging in
[viki] 1116593v: Downloading video JSON
[viki] 1116593v: Downloading video streams JSON
[viki] 1116593v: Downloading MPD manifest
WARNING: [viki] Unknown MIME type image/jpeg in DASH manifest
ERROR: list index out of range
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/youtube_dlc/YoutubeDL.py", line 830, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dlc/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dlc/extractor/viki.py", line 319, in _real_extract
    subtitles[subtitle_lang] = [{
  File "/usr/local/lib/python3.8/dist-packages/youtube_dlc/extractor/viki.py", line 322, in <listcomp>
    'videos/%s/subtitles/%s.%s?stream_id=%s' % (video_id, subtitle_lang, subtitles_format, stream_ids[0])),
IndexError: list index out of range

[download] Downloading video 2 of 20
[viki] 1116518v: Downloading video JSON
[viki] 1116518v: Downloading video streams JSON
[viki] 1116518v: Downloading MPD manifest
WARNING: [viki] Unknown MIME type image/jpeg in DASH manifest
ERROR: list index out of range
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/youtube_dlc/YoutubeDL.py", line 830, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dlc/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dlc/extractor/viki.py", line 319, in _real_extract
    subtitles[subtitle_lang] = [{
  File "/usr/local/lib/python3.8/dist-packages/youtube_dlc/extractor/viki.py", line 322, in <listcomp>
    'videos/%s/subtitles/%s.%s?stream_id=%s' % (video_id, subtitle_lang, subtitles_format, stream_ids[0])),
IndexError: list index out of range```

**Comment by panda130** [comment]
I received the same error. This seems to be a recent development. When I download with normal youtube-dl, it just downloads an MPD file instead of the MP4 video file.

**Comment by blackjack4494** [comment]
It seems they changed some more actually.
@zackmark29
Apparently you are now able to download 1080p even when not being logged in.
Interestingly when you watch in the browser you will always get a drm protected version but the api still returns non drm protected ones. I wonder how long as in the past some regions already have been switching mostly to drm only.

I believe I got the error. Should be realted to stream_id which is needed to get correct subtitles.

**Comment by zackmark29** [comment]
Let me check later after my work

**Comment by zackmark29** [comment]
Actually with this url https://www.viki.com/videos/1116593v-strong-woman-do-bong-soon-special-episode-0, this is not DRM Protected.
You can just get the MPD url, instead of the actual url.
But I'll check later.

C:\_YDL\yt-dlc-master\yt-dlc-master>python -m youtube_dlc -F "https://manifest-viki.viki.io/v1/1116593v/akamai/main/mpd/normal/viki/high/hd/ww/na/manifest.mpd?u=17823381u&h_country=ph&h_data_center=sng&h_host=playback-streams-84c98f678b-6k7sf&h_timestamp=1604191939&tag=mpdhd%3Ahigh%3Aww%3AsourceVIKI%3Ampd%3Acached&app=100000a&sig=936112a3617a2a91d301291913baf237f462cb1b"
[generic] manifest: Requesting header
WARNING: Falling back on generic information extractor.
[generic] manifest: Downloading webpage
[generic] manifest: Extracting information
WARNING: [generic] Unknown MIME type image/jpeg in DASH manifest
[info] Available formats for manifest:
format code  extension  resolution note
6            m4a        audio only DASH audio   49k , m4a_dash container, mp4a.40.2 (48000Hz)
7            m4a        audio only DASH audio   65k , m4a_dash container, mp4a.40.2 (48000Hz)
5            m4a        audio only DASH audio   81k , m4a_dash container, mp4a.40.2 (48000Hz)
8            m4a        audio only DASH audio  193k , m4a_dash container, mp4a.40.2 (48000Hz)
9            m4a        audio only DASH audio  193k , m4a_dash container, mp4a.40.2 (48000Hz)
1            mp4        426x238    DASH video  280k , mp4_dash container, avc1.640015, 30fps, video only
2            mp4        640x360    DASH video  501k , mp4_dash container, avc1.64001E, 30fps, video only
3            mp4        852x480    DASH video  700k , mp4_dash container, avc1.64001F, 30fps, video only
4            mp4        1280x720   DASH video 1626k , mp4_dash container, avc1.64001F, 30fps, video only
0            mp4        1920x1080  DASH video 3884k , mp4_dash container, avc1.640028, 30fps, video only (best)

**Comment by blackjack4494** [comment]
There is a new way of obtaining stream_id. Before that `stream_id` was provided within the manifest.  
Now it's here  
https://www.viki.com/api/videos/1172595v  
The request must include `x-viki-app-ver: 4.0.57`  
It's the new-ish endpoint used for drm streams. This will be standard sooner or later.

**Comment by zackmark29** [comment]
@blackjack4494 the problem I think with getting the stream id's.

When I try to comment first the lines from 318 to 323, I can get this

[debug] Command-line args: ['--username', 'PRIVATE', '--password', 'PRIVATE', '-F', 'https://www.viki.com/videos/1116518v-strong-woman-do-bong-soon-episode-1', '-v']
[debug] Loading archive file None
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dlc version 2020.10.25
[debug] Python version 3.8.2 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 4.2.2, ffprobe 3.3.2
[debug] Proxy map: {}
[viki] Logging in
[viki] 1116518v: Downloading video JSON
[viki] 1116518v: Downloading video streams JSON
[viki] 1116518v: Downloading MPD manifest
WARNING: [viki] Unknown MIME type image/jpeg in DASH manifest
[info] Available formats for 1116518v:
format code  extension  resolution note
mpd-http-6   m4a        audio only DASH audio   49k , m4a_dash container, mp4a.40.2 (48000Hz)
mpd-http-7   m4a        audio only DASH audio   65k , m4a_dash container, mp4a.40.2 (48000Hz)
mpd-http-5   m4a        audio only DASH audio   81k , m4a_dash container, mp4a.40.2 (48000Hz)
mpd-http-8   m4a        audio only DASH audio  193k , m4a_dash container, mp4a.40.2 (48000Hz)
mpd-http-9   m4a        audio only DASH audio  193k , m4a_dash container, mp4a.40.2 (48000Hz)
mpd-http-1   mp4        426x238    DASH video  234k , mp4_dash container, avc1.640015, 24fps, video only
mpd-http-2   mp4        640x360    DASH video  456k , mp4_dash container, avc1.64001E, 24fps, video only
mpd-http-3   mp4        852x480    DASH video  703k , mp4_dash container, avc1.64001E, 24fps, video only
mpd-http-4   mp4        1280x720   DASH video 1405k , mp4_dash container, avc1.64001F, 24fps, video only (best)

**Comment by blackjack4494** [comment]
fixed here https://github.com/blackjack4494/yt-dlc/commit/ae306df7e0e20866e39cc4f817edb99fe47ddc4d

**Comment by zackmark29** [comment]
> 4.0.57

haha I like the new API update. Looks like they are going to upgrade all endpoints and APIS soon

**Comment by panda130** [comment]
@blackjack4494 I am so impressed! Thank you very much for your super fast response. I really appreciate your talent and hard work.

I noticed that after you made the fix, the maximum resolution I can see with youtube-dlc is 720p. Before, youtube-dlc was able to find 1080p versions of the videos. Is there any way to access the 1080p versions?

Here is a sample video that previously had 1080p available.

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--skip-download', '--list-formats', '-u', 'PRIVATE', '-p', 'PRIVATE', 'https://www.viki.com/videos/1172595v-search-episode-1']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dlc version 2020.10.25
[debug] Python version 3.7.7 (CPython) - Darwin-16.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1.4, ffprobe 4.1.4, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[viki] Logging in
[viki] 1172595v: Downloading video JSON
[viki] 1172595v: Downloading video streams JSON
[viki] 1172595v: Downloading MPD manifest
WARNING: [viki] Unknown MIME type image/jpeg in DASH manifest
[viki] 1172595v: Downloading new video JSON to get subtitles
[info] Available formats for 1172595v:
format code  extension  resolution note
mpd-http-6   m4a        audio only DASH audio   49k , m4a_dash container, mp4a.40.2 (48000Hz)
mpd-http-7   m4a        audio only DASH audio   65k , m4a_dash container, mp4a.40.2 (48000Hz)
mpd-http-5   m4a        audio only DASH audio   81k , m4a_dash container, mp4a.40.2 (48000Hz)
mpd-http-8   m4a        audio only DASH audio  193k , m4a_dash container, mp4a.40.2 (48000Hz)
mpd-http-9   m4a        audio only DASH audio  193k , m4a_dash container, mp4a.40.2 (48000Hz)
mpd-http-1   mp4        426x238    DASH video  218k , mp4_dash container, avc1.640015, 30fps, video only
mpd-http-2   mp4        640x360    DASH video  426k , mp4_dash container, avc1.64001E, 30fps, video only
mpd-http-3   mp4        852x480    DASH video  682k , mp4_dash container, avc1.64001F, 30fps, video only
mpd-http-4   mp4        1280x720   DASH video 1381k , mp4_dash container, avc1.64001F, 30fps, video only (best)
```

**Comment by blackjack4494** [comment]
@panda130 hm I did not change anything about the rest. Only subtitles :o

**Comment by zackmark29** [comment]
@panda130 on some mpd doesn't have 1080p

**Comment by zackmark29** [comment]
1080p only available for MPD with DRM Protected
If you know how to download =D
But me I can download it and black as well

**Comment by zackmark29** [comment]
> @panda130 hm I did not change anything about the rest. Only subtitles :o
> 
> But as I said they moved some links in manifests. Maybe this needs further adaption tho.

yeah almost all their latest series you can get 1080p only available on DRM Protected. 
But If I have time later I will take a look some changes on the streams

**Comment by blackjack4494** [comment]
This
`WARNING: [viki] Unknown MIME type image/jpeg in DASH manifest`
is actually just a link to another manifest (mpd) which also contains the 1080p stream and you don't need any authorization. But I haven't tested yet whether it is actually drm or not BUT it seems to be without.

**Comment by zackmark29** [comment]
> This
> `WARNING: [viki] Unknown MIME type image/jpeg in DASH manifest`
> is actually just a link to another manifest (mpd) which also contains the 1080p stream and you don't need any authorization. But I haven't tested yet whether it is actually drm or not BUT it seems to be without.

yes it has the mpd url same from browser with 1080p
but it's not available on some url.

**Comment by blackjack4494** [comment]
The linked manifest contains 1080p (and lower res as well) without drm.  
This is funny because you don't need to be logged in.

**Comment by zackmark29** [comment]
> The linked manifest contains 1080p (and lower res as well) without drm.
> This is funny because you don't need to be logged in.
> 
> @zackmark29
> So far every single video I tried had the 1080p manifest in it. The 'some light' link you gave as an example isn't working for me because of geo restrictions. I believe all available at least in Europe now have 1080p but rather by mistake lol.

yeah because I get that  link with VPN connected to UK
maybe depends on the location. So we have to find where the permanent location available all 1080p
But so far for now, I only downloading DRM protected because of  better quality I think
