### ISSUE TITLE
Can’t process leading dash “-“ on YouTube video IDs

### ISSUE THREAD

**Issue by SKnight79** [blackjack4494/yt-dlc#88]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dlc version **2020.10.31**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

/usr/local/bin/youtube-dl '-EGWaavWkEU' --default-search 'ytsearch'
                                 
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: no such option: -E

## Description

Any YouTube video ID with a leading dash seems to cause the program to think it's an option being selected. I've tried single and double quoting it with no success.

**Comment by insaneracist** [comment]
double dash signals end of options
`youtube-dlc -- -EGWaavWkEU` 
or use full url `youtube-dlc "https://www.youtube.com/watch?v=-EGWaavWkEU"`

**Comment by SKnight79** [comment]
That worked! Thanks for the tip!
