### ISSUE TITLE
redirect youtube-dlc output to own graphics

### ISSUE THREAD

**Issue by Jochen-sys** [blackjack4494/yt-dlc#94]
Hello, is there a way that instead of seeing the output of youtube-dlc in the shell, I can also write it into my own graphics? So that I see in the graphic how far the download is?

**Comment by dirkf** [comment]
* try `--external-downloader ffmpeg` and `--external-downloader-args "-progress yourURL"`
* or RTFM "EMBEDDING YOUTUBE-DL ... set a logger object"
* https://github.com/tqdm/tqdm might be helpful.

**Comment by Jochen-sys** [comment]
First of all, thanks for answering.
But what is tqdm useful for? I think for that I would have to know how fast the video is downloading and how big the video is (in bytes). But I don't know how to find out.
And I don't really know what the first two posssibilities stand for. I can think myself about the first possibility a little bit. But what do you mean with the second one?

**Comment by dirkf** [comment]
On 01/11/2020 13:06, Jochen-sys wrote:
> First of all, thanks for answering.
> But what is tqdm useful for? I think for that I would have to know how fast the video is downloading and how big the video is (in bytes). But I don't know how to find out.
> And I don't really know what the first two possibilities stand for. I can think myself about the first possibility a little bit. But what do you mean with the second one?
>

According to the documentation, if you embed yt-dl[c] in a Python
wrapper you can hook the output. You may have a problem that the output
depends on whether yt-dl downloads the target itself or uses a helper
program, which is why I suggested option 1.

You might also investigate how the --console-title option works. Maybe
you can patch yt-dl to output progress information in a known format.

When you have some progress data in a known format, something like tqdm
could help you to display it. There are plenty of similar tools.

/df

--
London SW6
UK

**Comment by Jochen-sys** [comment]
Sadly I don't know really how to use option 1. But when I try this:
youtube-dlc    --external-downloader ffmpeg --external-downloader-args https://www.youtube.com/watch?v=Yc7-krRX8uA -f best https://www.youtube.com/watch?v=Yc7-krRX8uA
It doesn't really do something diferent as when I write:
youtube-dlc     -f best https://www.youtube.com/watch?v=Yc7-krRX8uA
.

Do I have to write the --console-title option like that?:
youtube-dlc     -f best https://www.youtube.com/watch?v=Yc7-krRX8uA --console-title

**Comment by dirkf** [comment]
On 01/11/2020 14:42, Jochen-sys wrote:
> Sadly I don't know really how to use option 1. But when I try this:
> youtube-dlc    --external-downloader ffmpeg --external-downloader-args https://www.youtube.com/watch?v=Yc7-krRX8uA -f best https://www.youtube.com/watch?v=Yc7-krRX8uA

Try

youtube-dlc    --external-downloader ffmpeg --external-downloader-args
-progress myfile.txt -f best https://www.youtube.com/watch?v=Yc7-krRX8uA

and monitor myfile.txt. I hear the pipe:1 can be used to send output to
stdout, and pipe:2 stderr.

> It doesn't really do something diferent as when I write:
> youtube-dlc     -f best https://www.youtube.com/watch?v=Yc7-krRX8uA
> ..
>
> Do I have to write the --console-title option like that?:
> youtube-dlc     -f best https://www.youtube.com/watch?v=Yc7-krRX8uA --console-title

Probs.

/df

--
London SW6
UK

**Comment by Jochen-sys** [comment]
So I tried the first one and it gave me an error. I solved it by writing:
youtube-dlc    --external-downloader ffmpeg --external-downloader-args -progress ytsearch:myfile.txt -f best https://www.youtube.com/watch?v=Yc7-krRX8uA
but that didn't do what I wished it to do.

Then I tried the version with --console-title, but I didn't find a difference to the normal order.

Now I'm trying to find out how I can check the download speed. Do  you know where it is written in the youtube-dlc code?

**Comment by deepesh-agarwal** [comment]
> youtube-dlc --external-downloader ffmpeg --external-downloader-args -progress myfile.txt -f best https://www.youtube.com/watch?v=Yc7-krRX8uA

This produces the error : `ERROR: u'myfile.txt' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dlc "ytsearch:myfile.txt" ) to search YouTube`

**Comment by dirkf** [comment]
On 05/11/2020 02:50, deepesh-agarwal wrote:
>> youtube-dlc --external-downloader ffmpeg --external-downloader-args -progress myfile.txt -f best https://www.youtube.com/watch?v=Yc7-krRX8uA
>
> This produces the error : `ERROR: u'myfile.txt' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dlc "ytsearch:myfile.txt" ) to search YouTube`
>

It thinks the download URL is myfile.txt because the parameter of
--external-downloader-args wasn't quoted (which depends on your command
shell, but might involve ""):

youtube-dlc --external-downloader ffmpeg --external-downloader-args
"-progress myfile.txt" -f best https://www.youtube.com/watch?v=Yc7-krRX8uA

/df

--
London SW6
UK
