### ISSUE TITLE
Run while you can! Leave Github!

### ISSUE THREAD

**Issue by Sanyy** [blackjack4494/yt-dlc#96]
I'm very grateful for this fork. I did not encountered any errors or difficulties so far, it simply works ... but : 

- we all know that this repo will be banned sooner or later just like youtube-dl's

Do you have any alternative site to publish this fork?

![youtube-dlc tar_RGB](https://user-images.githubusercontent.com/17810774/97802652-c396fd80-1c3c-11eb-99d7-bd825c6e0702.png)

**Comment by october262** [comment]
regular youtube-dl was just recently updated - https://www.videohelp.com/software/youtube-dl

**Comment by Sanyy** [comment]
Nice to hear it... I did not say it is dead.

**Comment by nicolaasjan** [comment]
GitHub Warns Users Reposting YouTube-DL They Could Be Banned...

https://torrentfreak.com/github-warns-users-reposting-youtube-dl-they-could-be-banned-201102/
https://old.reddit.com/r/DataHoarder/comments/jmm2i1/github_warns_users_reposting_youtubedl_they_could/

**Comment by Seirdy** [comment]
I [detailed instructions](https://github.com/blackjack4494/yt-dlc/issues/9#issuecomment-718952207) ([archived](https://web.archive.org/web/20201102163641/https://github.com/blackjack4494/yt-dlc/issues/9#issuecomment-718952207)) on how to painlessly set up remotes without having learn and depend on a web service; more info is available right in `man git-remote`.
Some others have suggested using CI/CD systems to automate this, but that means adding a point of failure by depending on (mostly US-based) web services. With this system, people with push access just have to add remotes just like they already do for the origin remote. I'm not suggesting that anybody learns anything new; if you've added a remote after running `git init`, *you've done this before.* Don't add more tools to your stack, esp. if those tools are web services that can be taken down.

**Comment by xloem** [comment]
Linking more obviously to #9 which has a lot of information on this topic.

**Comment by TheFrenchGhosty** [comment]
This is fearmongering. Github won't delete the repo unless it receives a DMCA for it. If this happen it's a non issue it's already mirrored in a lot of places.

Github threatening to ban, doesn't mean anyone will be ban, it just means that they can ban you if you do it again.

Really stop worrying.

**Comment by xloem** [comment]
It's a supportive joke, Ghosty.  We are strong enough to move off github, which rudely accepted a random dmca to a busy lone developer of a hugely popular project without providing any significant aid in filing a strong counternotice, and are excited about doing so.

**Comment by ajayyy** [comment]
@xloem what do you mean? The CEO of GitHub joined IRC and chatted with the developer

**Comment by VADemon** [comment]
They only wanted ydl to comply with the allegations and admit guilt, to get the repo reinstated.

WHETHER OR NOT Github is willing to really help - only time can tell.

**Comment by xloem** [comment]
> @xloem what do you mean? The CEO of GitHub joined IRC and chatted with the developer. They definitely are trying to help

Well, there are over ten thousand of us with blocked forks and the ceo asked the maintainer to remove portions of the code rather than talking more about counternotices.  It seems like you can send a DMCA notice about anything to anyone to get arbitrary stuff taken down, and nobody files counternotices because the person who filed the initial notice can sue.  Can't you sue people all the time anyway?  If this were a gnu service I just really don't think this would be going the same.

Nonetheless I think it's really great that the CEO came into the chat publicly to talk personally to the maintainer and a tiny bit to the development community, and I think there must be a way to work with github to help communities be more resilient to things like this in the future, by supporting decentralized tools or somesuch.

**Comment by TheFrenchGhosty** [comment]
>the ceo asked the maintainer to remove portions of the code rather than talking more about counternotices

Proof?

This is a rumor, everything that was said between the maintainer and the Github CEO was kept private.

**Comment by xloem** [comment]
Sorry you're out of the loop.  Come by #youtube-dl Inc.freenode.net yourself and hang out for a while.  Here's a censored log: https://cache.tehsausage.com/ytdl/words.txt

**Comment by AlephAlpha** [comment]
Would it be possible to put the code on some blockchain?

**Comment by xloem** [comment]
That's wholly possible.  I hacked https://github.com/xloem/git-remote-bsv quickly together once but I think it's not functioning now and needs some small work.  Git repos are just data, it's reasonable to make a blockchain remote for them.  I've been focusing on migrating issues to git-bug but can help with blockchains if there's interest/necessity.
